apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use the same base as dev
resources:
- ../../base
- ingress.yaml

# Preview environments deploy to dev namespace
# but get unique resource names from ResourceSet
namespace: dev

# Inherit most configuration from base
# ResourceSet patches will override:
# - deployment name: banterbus → banterbus-mr-123
# - service name: banterbus → banterbus-mr-123
# - ingress host: dev.banterbus.games → mr-123.banterbus.games
# - image tag: latest → feature-branch-sha8

# Optional: Preview-specific configurations
patches:
- path: preview-patches.yaml
