# Service that dynamically routes to preview environment pods
# This uses labels to identify which pods belong to which preview environment

apiVersion: v1
kind: Service
metadata:
  name: banterbus-preview-router
  namespace: dev
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: http
spec:
  selector:
    app: banterbus
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

---
# Middleware to add preview environment identification
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: preview-env-headers
  namespace: dev
spec:
  headers:
    customRequestHeaders:
      X-Preview-Environment: "true"
      # This will be set dynamically by the ingress
      
---
# IngressRoute for dynamic preview environment routing
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: banterbus-preview-router
  namespace: dev
spec:
  entryPoints:
    - websecure
  routes:
    # Route for preview environments (mr-*.banterbus.games)
    - match: HostRegexp(`mr-{id:[0-9]+}.banterbus.games`)
      kind: Rule
      services:
        - name: banterbus-preview-router
          port: 80
      middlewares:
        - name: preview-env-headers
  tls:
    certResolver: letsencrypt-prod