_commit: v0.1.1
_src_path: https://gitlab.com/hmajid2301/nix-go-htmx-tailwind-template
gitlab_url: https://gitlab.com/hmajid2301/banterbus
gitlab_username: hmajid2301
project_slug: banterbus
project_title: Banter Bus
service_prefix: BANTERBUS
short_description: Banter Bus is a web application video game, inspired by other party games like JackBox.
