run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    # - bodyclose
    # - dogsled
    # - dupl
    # - errcheck
    # - copyloopvar
    # # - funlen
    # - gochecknoinits
    # - goconst
    # - gocritic
    # - gocyclo
    # - gofmt
    # - goimports
    # - mnd
    # - goprintffuncname
    # - gosec
    # - gosimple
    # - govet
    # - ineffassign
    # - lll
    # - misspell
    # - nakedret
    # - noctx
    # - nolintlint
    # - revive
    # - staticcheck
    # - stylecheck
    # - typecheck
    # - unconvert
    # - unparam
    # - unused
    # - whitespace

linters-settings:
  goimports:
    local-prefixes: gitlab.com/hmajid2301/banterbus

issues:
  exclude-dirs:
    - .go
    - direnv

  exclude-rules:
    - path: _test.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
