with-expecter: true
dir: "internal/{{.PackageName}}/mocks"
filename: "mock_{{ .InterfaceName | lower }}.go"
packages:
  gitlab.com/hmajid2301/banterbus/internal/service:
    interfaces:
      Storer: {}
      Randomizer: {}
  gitlab.com/hmajid2301/banterbus/internal/transport/websockets:
    interfaces:
      RoundServicer: {}
      LobbyServicer: {}
      PlayerServicer: {}
      Websocketer: {}
