all: false
filename: "{{ .InterfaceName | lower }}.go"
dir: '{{.InterfaceDir}}/mocks'
packages:
  gitlab.com/hmajid2301/banterbus/internal/service:
    interfaces:
      Randomizer:
      Storer:
  gitlab.com/hmajid2301/banterbus/internal/transport/websockets:
    interfaces:
      LobbyServicer:
      PlayerServicer:
      RoundServicer:
      State:
      WSHandler:
      Websocketer:
