all: false
filename: "{{ .InterfaceName | lower }}.go"
dir: '{{.InterfaceDir}}/mocks'
packages:
  gitlab.com/hmajid2301/banterbus/internal/service:
    interfaces:
      Randomizer:
      LobbyStore:
      PlayerStore:
      QuestionStore:
      RoundStore:
  gitlab.com/hmajid2301/banterbus/internal/transport/websockets:
    interfaces:
      LobbyServicer:
      PlayerServicer:
      RoundServicer:
      WSHandler:
      Websocketer:
  gitlab.com/hmajid2301/banterbus/internal/statemachine:
    interfaces:
      RoundService:
      ClientUpdater:
      StateTransitioner:
      State:
