services:
  otel-collector:
    image: otel/opentelemetry-collector-dev:latest
    ports:
      - 4317:4317
      - 55680:55680

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
