services:
  redis:
    image: redis:8.2.1
    profiles:
      - test
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17.6
    profiles:
      - test
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banterbus
      POSTGRES_HOST_AUTH_METHOD: trust
      # Performance tuning for CI/tests
      POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
    command:
      - "postgres"
      # Essential connection settings
      - "-c"
      - "max_connections=1000"
      # Performance optimizations for CI/test environments
      - "-c"
      - "fsync=off"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "full_page_writes=off"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      # Logging for debugging
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_min_messages=INFO"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -d banterbus"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

  migrate:
    image: gomicro/goose:3.25.0
    profiles:
      - test
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banterbus
    command: [
      "goose", "-dir", "/migrations", "postgres",
      "host=postgres port=5432 user=postgres password=postgres dbname=banterbus sslmode=disable",
      "up"
    ]
    volumes:
      - ./internal/store/db/sqlc/migrations:/migrations:ro
    restart: "no"

  seed-data:
    image: postgres:17.6
    profiles: [test]
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: banterbus
    volumes:
      - ./docker/postgres-init/01-seed-data.sql:/seed-data.sql:ro
    command: psql -f /seed-data.sql
    restart: "no"

  oauth2:
    image: ghcr.io/navikt/mock-oauth2-server:2.3.0
    profiles:
      - test
    ports:
      - 9091:8080
    # healthcheck:
    #   test: ["CMD-SHELL", "nc -z 127.0.0.1 8080 || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  smocker:
    image: ghcr.io/smocker-dev/smocker:1.0.0
    profiles:
      - other
    ports:
      - 44300:8080
      - 44301:8081

  alloy:
    image: grafana/alloy:v1.10.2
    profiles:
      - monitoring
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "--storage.path=/var/lib/alloy/data",
        "--stability.level=public-preview",
        "/etc/alloy/config.alloy",
      ]
    ports:
      - 4317:4317
      - 4318:4318
      - 12345:12345
    volumes:
      - ./docker/config.alloy:/etc/alloy/config.alloy
    depends_on:
      - tempo
      - loki
      - mimir

  mimir:
    image: grafana/mimir:2.17.1
    profiles:
      - monitoring
    command:
      - "-auth.multitenancy-enabled=false"
      - "-auth.no-auth-tenant=anonymous"
      - "-config.file=/etc/mimir/config.yaml"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/ready"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 20
    volumes:
      - ./docker/mimir.yaml:/etc/mimir/config.yaml
      - mimir-data:/data

  grafana:
    image: grafana/grafana:11.6.6
    profiles:
      - monitoring
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
     - ./docker/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml:ro
     - ./docker/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
     - ./dashboards/grafana.json:/etc/grafana/provisioning/dashboards/grafana.json:ro
     - grafana-data:/var/lib/grafana

  tempo:
    image: grafana/tempo:2.8.2
    profiles:
      - monitoring
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./docker/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3200/ready"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 20

  loki:
    image: grafana/loki:3.5.5
    profiles:
      - monitoring
    command: ["-config.file=/etc/loki/loki-config.yaml"]
    volumes:
      - ./docker/loki.yaml:/etc/loki/loki-config.yaml
      - loki-data:/loki

volumes:
  postgres-data:
  grafana-data:
  mimir-data:
  tempo-data:
  loki-data:
