services:
  otel-collector:
    image: otel/opentelemetry-collector:0.107.0
    ports:
      - 4317:4317
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
    volumes:
      - ./docker/otelcol.yaml:/etc/otelcol/config.yaml

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      JAEGER_PROPAGATION: w3c
    ports:
      - 16686:16686
    healthcheck:
      test: [CMD, wget, -q, -S, -O, "-", "localhost:14269"]

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.4.0
    ports:
      - 3000:3000

  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16.6
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
