schema = 3

[mod]
  [mod."github.com/a-h/templ"]
    version = "v0.2.793"
    hash = "sha256-WThPVkb56osTrMJZf0WIoqbsM9DHGaZsG47MS0eoseA="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/deckarep/golang-set/v2"]
    version = "v2.6.0"
    hash = "sha256-ni1XK75Q8iBBmxgoyZTedP4RmrUPzFC4978xB4HKdfs="
  [mod."github.com/dgryski/go-rendezvous"]
    version = "v0.0.0-20200823014737-9f7001d12a5f"
    hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.6"
    hash = "sha256-W/uPcE22Fduw1XmX8Ujf1S9SYVOcEoE1wzK4I0/vapw="
  [mod."github.com/go-jose/go-jose/v3"]
    version = "v3.0.3"
    hash = "sha256-PsjN1vVhAFI6X11iIkpQU4i7Ax6FvkhXNxApeBa2BvA="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.2"
    hash = "sha256-/W6qGilFlZNTb9Uq48xGZ4IbsVeSwJiAMLw4wiNYHLI="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.1"
    hash = "sha256-ixcJ2RrK1ZH3YWGQZF9QFBo02NOuLeSp9wJ7gniipgY="
  [mod."github.com/gobwas/httphead"]
    version = "v0.1.0"
    hash = "sha256-6wFni/JkK2GqtVs3IW+GxHRNoSu4EJfzaBRGX2hF1IA="
  [mod."github.com/gobwas/pool"]
    version = "v0.2.1"
    hash = "sha256-py8/+Wo5Q83EbYMUKK5U/4scRcyMo2MjOoxqi5y+sUY="
  [mod."github.com/gobwas/ws"]
    version = "v1.4.0"
    hash = "sha256-I3BWBluCakfFuTKkwi5Dh+DlzpdcizOAxa4lKOUo8Ak="
  [mod."github.com/gomig/avatar"]
    version = "v1.0.3"
    hash = "sha256-6L2wF8eAdp8bChCMkP0KIgxHm/ak1mnNtrt2FUQm1Pc="
  [mod."github.com/gomig/utils"]
    version = "v1.0.1"
    hash = "sha256-jOQKphQVuLEuKsMY7s2sj8CPYFkQUs7o8uYELo7s4LQ="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/invopop/ctxi18n"]
    version = "v0.9.0"
    hash = "sha256-Qhyim2NQC/ofcpxN+cIookNwQahclhNld86VN/uDemw="
  [mod."github.com/invopop/yaml"]
    version = "v0.3.1"
    hash = "sha256-7x9sX9nc0ZL1+Fqh6hX+9ALNPXlIeCCkhGnwHR1VW0c="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.1"
    hash = "sha256-N0aiHG91gMztyWC3PAEG0JVd6B/yrcOCfdl0NzqCDXk="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.11"
    hash = "sha256-LFSIWy0C4VbiuPve0eKHr7Q7s4XtaGzsZ3qpO+6bEgc="
  [mod."github.com/lmittmann/tint"]
    version = "v1.0.5"
    hash = "sha256-NthPT7c1Q2VSp5IrWMGAvzX7AxEcTKk+O0F56pgaTsQ="
  [mod."github.com/mfridman/interpolate"]
    version = "v0.0.2"
    hash = "sha256-3u04CYOy7PLMctdkum5pltSTkYya8EfXJexbW7j0KB8="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/playwright-community/playwright-go"]
    version = "v0.4802.0"
    hash = "sha256-Ae++UhS+NYfoeQwlIZmHdzxs7RfDp7KV4jma/AbX32c="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/pressly/goose/v3"]
    version = "v3.23.0"
    hash = "sha256-DKjiXQcUQ1ZNAwsqo3xfwMOk2Ah4fPXMjFiGKgRRx04="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.20.5"
    hash = "sha256-RbDZTBH+j2ZNLbHSMFxW0j8UStvkwc4IHTz3My9w4qo="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.1"
    hash = "sha256-rIDyUzNfxRA934PIoySR0EhuBbZVRK/25Jlc/r8WODw="
  [mod."github.com/prometheus/common"]
    version = "v0.60.1"
    hash = "sha256-6ZSm800o6QjFKi5QUs/Zsjqq3i+V8UFvkGqR7lWqJ2M="
  [mod."github.com/prometheus/procfs"]
    version = "v0.15.1"
    hash = "sha256-H+WXJemFFwdoglmD6p7JRjrJJZmIVAmJwYmLbZ8Q9sw="
  [mod."github.com/redis/go-redis/v9"]
    version = "v9.7.0"
    hash = "sha256-lpEMK1jBuwrIY7nrk5f9Ru4Y2FXDU4FxlVjXHjV5Ahc="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.13.1"
    hash = "sha256-fD4n3XVDNHL7hfUXK9qi31LpBVzWnRK/7LNc3BmPtnU="
  [mod."github.com/sethvargo/go-envconfig"]
    version = "v1.1.0"
    hash = "sha256-WelRHfyZG9hrA4fbQcfBawb2ZXBQNT1ourEYHzQdZ4w="
  [mod."github.com/sethvargo/go-retry"]
    version = "v0.3.0"
    hash = "sha256-1ZnFRHAaQjralGKVRoCbiwCXXB3w4kS3f+2hK9S8lbU="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.2"
    hash = "sha256-VKYxrrFb1nkX6Wu3tE5DoP9+fCttwSl9pgLN6567nck="
  [mod."github.com/stretchr/testify"]
    version = "v1.10.0"
    hash = "sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI="
  [mod."github.com/veqryn/slog-context"]
    version = "v0.7.0"
    hash = "sha256-eCdqk/nS9o/Zsgi2q9425dRyrXCWKHNS8VG1hI352mU="
  [mod."github.com/vgarvardt/pgx-google-uuid/v5"]
    version = "v5.6.0"
    hash = "sha256-F+E8rFEHnmJKcCxl4hA3MosSEKqxytp5y7VMVZLFQEg="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.57.0"
    hash = "sha256-cvG6gfqfX3IasDlC8SeS7u1sp3LG9ezbX+hU5LyWKBY="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.32.0"
    hash = "sha256-Z2PoBBncuUkAksk8wT4lW6+uUu1wg24sGfwIYozIzaY="
  [mod."go.opentelemetry.io/otel/exporters/prometheus"]
    version = "v0.54.0"
    hash = "sha256-vsX+WXKIF522ChUHLmVGECF0Z43uW/nXZi7oqezhpz4="
  [mod."go.opentelemetry.io/otel/exporters/stdout/stdouttrace"]
    version = "v1.32.0"
    hash = "sha256-KQHeQWC7vrQmBmr+7MCHO5b22mMBcsF7HUX6va0uXhc="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.32.0"
    hash = "sha256-f2H8itkQflk/m98dSk1TCv37wvsnMojaGNZRJ6BcksU="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.32.0"
    hash = "sha256-Momq9xYr7USKmWndBhTwNiO90XgcrxH1+eCs1woyIlo="
  [mod."go.opentelemetry.io/otel/sdk/metric"]
    version = "v1.32.0"
    hash = "sha256-sQvM00thVv1zhOsC2PH8eVCCpjU1KjIX9VtntR8Z5+I="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.32.0"
    hash = "sha256-WtOrB2L8wQFiMb5BHK7a6FTw2wb3rW495whNjzdxC1I="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."golang.org/x/crypto"]
    version = "v0.29.0"
    hash = "sha256-sqckobR2VWucCgb7xpY2wLktnAA+XyXJbhCm80yCo78="
  [mod."golang.org/x/net"]
    version = "v0.31.0"
    hash = "sha256-G+vGyCnn8jywmX3KvsIwhZkOv3+oAERNNeCeiQqfIL0="
  [mod."golang.org/x/sync"]
    version = "v0.9.0"
    hash = "sha256-sGvzGqaaXE5dxohKkpbJMnu+bMmismsSqr8YMtrK+Rc="
  [mod."golang.org/x/sys"]
    version = "v0.27.0"
    hash = "sha256-BXQcF9RrJ55Pq7Nl67TeFGkgkyuKkQ8hHKN4/L4ggWc="
  [mod."golang.org/x/text"]
    version = "v0.20.0"
    hash = "sha256-YP8zSo2e9okqhxVB8me8sJyij2O0tTQEg5t+8bsIUx8="
  [mod."google.golang.org/protobuf"]
    version = "v1.35.1"
    hash = "sha256-4NtUQoBvlPGFGjo7c+E1EBS/sb8oy50MGy45KGWPpWo="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."modernc.org/gc/v3"]
    version = "v3.0.0-20241004144649-1aea3fae8852"
    hash = "sha256-nwh2xVgoeq97cSzcOQShyraromxAkYa0vCym8LqRQG4="
