schema = 3

[mod]
  [mod."github.com/MicahParks/jwkset"]
    version = "v0.5.19"
    hash = "sha256-V1cEZpzrI5somHmwm9f4esse6FzAnlgynsFXHl0D2ko="
  [mod."github.com/MicahParks/keyfunc/v3"]
    version = "v3.3.5"
    hash = "sha256-+wRv4O0le3fz+Hanun7ukRad050lRN9OanPTT9wchPA="
  [mod."github.com/a-h/templ"]
    version = "v0.2.793"
    hash = "sha256-WThPVkb56osTrMJZf0WIoqbsM9DHGaZsG47MS0eoseA="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.3.0"
    hash = "sha256-wfVjNZsGG1WoNC5aL+kdcy6QXPgZo4THAevZ1787md8="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/deckarep/golang-set/v2"]
    version = "v2.6.0"
    hash = "sha256-ni1XK75Q8iBBmxgoyZTedP4RmrUPzFC4978xB4HKdfs="
  [mod."github.com/dgryski/go-rendezvous"]
    version = "v0.0.0-20200823014737-9f7001d12a5f"
    hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="
  [mod."github.com/exaring/otelpgx"]
    version = "v0.7.0"
    hash = "sha256-HCenlYqPcXVb9zqBQGZhtWOq+tX2xwGlCIDlKCxzXws="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/go-jose/go-jose/v3"]
    version = "v3.0.3"
    hash = "sha256-PsjN1vVhAFI6X11iIkpQU4i7Ax6FvkhXNxApeBa2BvA="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.2"
    hash = "sha256-/W6qGilFlZNTb9Uq48xGZ4IbsVeSwJiAMLw4wiNYHLI="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.1"
    hash = "sha256-ixcJ2RrK1ZH3YWGQZF9QFBo02NOuLeSp9wJ7gniipgY="
  [mod."github.com/gobwas/httphead"]
    version = "v0.1.0"
    hash = "sha256-6wFni/JkK2GqtVs3IW+GxHRNoSu4EJfzaBRGX2hF1IA="
  [mod."github.com/gobwas/pool"]
    version = "v0.2.1"
    hash = "sha256-py8/+Wo5Q83EbYMUKK5U/4scRcyMo2MjOoxqi5y+sUY="
  [mod."github.com/gobwas/ws"]
    version = "v1.4.0"
    hash = "sha256-I3BWBluCakfFuTKkwi5Dh+DlzpdcizOAxa4lKOUo8Ak="
  [mod."github.com/golang-jwt/jwt/v5"]
    version = "v5.2.1"
    hash = "sha256-3AMtL0kAD5L2/3eHf/Q6+hqga8mEaeEs+Hcdlx65go4="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.24.0"
    hash = "sha256-U1+nKMAhHQ9KQkEbSRolahAt2toMxI0x1X/6/TJzAbg="
  [mod."github.com/invopop/ctxi18n"]
    version = "v0.9.0"
    hash = "sha256-Qhyim2NQC/ofcpxN+cIookNwQahclhNld86VN/uDemw="
  [mod."github.com/invopop/yaml"]
    version = "v0.3.1"
    hash = "sha256-7x9sX9nc0ZL1+Fqh6hX+9ALNPXlIeCCkhGnwHR1VW0c="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.2"
    hash = "sha256-FEh0GwrkTlFPZiqT6m3jYg5OV62/LHs/otMQuJfcMNw="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."github.com/lmittmann/tint"]
    version = "v1.0.6"
    hash = "sha256-toT4YdhajyOXWzOHFxpMLbx9uJyCBEP36BR0FWy1H0A="
  [mod."github.com/mdobak/go-xerrors"]
    version = "v0.3.1"
    hash = "sha256-/RkHFCPT8CoQtgy3FDu9JZwVFRH1fnPdMW5dbqVWqAM="
  [mod."github.com/mfridman/interpolate"]
    version = "v0.0.2"
    hash = "sha256-3u04CYOy7PLMctdkum5pltSTkYya8EfXJexbW7j0KB8="
  [mod."github.com/playwright-community/playwright-go"]
    version = "v0.4901.0"
    hash = "sha256-OUW+oD14IpBQu22E8BtZh01qQo4R7XJQlv3Cv+Ja+Vk="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/pressly/goose/v3"]
    version = "v3.24.0"
    hash = "sha256-KT1Q4eeQLv1j3uBQOmM90ufWeBuZ7SFqyheiNmxuxnk="
  [mod."github.com/redis/go-redis/extra/rediscmd/v9"]
    version = "v9.7.0"
    hash = "sha256-52BY3n/W63/9oAhGYPtSZzyxh/BY6Oo0lLKsxUzROEw="
  [mod."github.com/redis/go-redis/extra/redisotel/v9"]
    version = "v9.7.0"
    hash = "sha256-KaAC6Mhvl7SovecFPxmw1DTA7PEIK4UfVZ1PEL7z2tE="
  [mod."github.com/redis/go-redis/v9"]
    version = "v9.7.0"
    hash = "sha256-lpEMK1jBuwrIY7nrk5f9Ru4Y2FXDU4FxlVjXHjV5Ahc="
  [mod."github.com/remychantenay/slog-otel"]
    version = "v1.3.2"
    hash = "sha256-fQN8r+CnyiVLgCHybK62der+t4nii53h2jGhEg4OGxQ="
  [mod."github.com/sethvargo/go-envconfig"]
    version = "v1.1.0"
    hash = "sha256-WelRHfyZG9hrA4fbQcfBawb2ZXBQNT1ourEYHzQdZ4w="
  [mod."github.com/sethvargo/go-retry"]
    version = "v0.3.0"
    hash = "sha256-1ZnFRHAaQjralGKVRoCbiwCXXB3w4kS3f+2hK9S8lbU="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.2"
    hash = "sha256-VKYxrrFb1nkX6Wu3tE5DoP9+fCttwSl9pgLN6567nck="
  [mod."github.com/stretchr/testify"]
    version = "v1.10.0"
    hash = "sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI="
  [mod."github.com/veqryn/slog-context"]
    version = "v0.7.0"
    hash = "sha256-eCdqk/nS9o/Zsgi2q9425dRyrXCWKHNS8VG1hI352mU="
  [mod."github.com/vgarvardt/pgx-google-uuid/v5"]
    version = "v5.6.0"
    hash = "sha256-F+E8rFEHnmJKcCxl4hA3MosSEKqxytp5y7VMVZLFQEg="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.1.0"
    hash = "sha256-cA9qCCu8P1NSJRxgmpfkfa5rKyn9X+Y/9FSmSd5xjyo="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.58.0"
    hash = "sha256-iqTPHfR1wXZY/yVTWtRBMjWlZkRxasaBGNhsNWHYxGw="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.33.0"
    hash = "sha256-NdAEEIqa81WLpDJbz4aCR4Ha/WnZcHPXY7d/jSu7H/k="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp"]
    version = "v1.33.0"
    hash = "sha256-1hn1Xw2RuqbvYCTqEvqz2DJng+HlUkfEqUtFnltzv/k="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.33.0"
    hash = "sha256-D5BMzmtN1d3pRnxIcvDOyQrjerK1JoavtYjJLhPKv/I="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"]
    version = "v1.33.0"
    hash = "sha256-xohWJeEN8WKJEggB/m14uR7SSi9eU3uao1qVGTsZQr0="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.33.0"
    hash = "sha256-bYr//1svQZ/uVWveaJGAxTpq0/rsFnDHKE6H2gVdce8="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.33.0"
    hash = "sha256-Xjganq6DesGN9XJUn+JDoKhwJKJ0H/PYzNcZw4qzNno="
  [mod."go.opentelemetry.io/otel/sdk/metric"]
    version = "v1.33.0"
    hash = "sha256-WUNznTdJUw9yy9GY/mKrqmOWaGw0YYIpyuZcd53kdUE="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.33.0"
    hash = "sha256-2bDa27eZT0+JHcDzV+MMCGKKYs7eYuTtGHIlbE0/gpk="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.4.0"
    hash = "sha256-XtEbLJmAUoKrvsMmIEJ0TdIjJXWG+z0X1cKECWQjl4Q="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."golang.org/x/crypto"]
    version = "v0.31.0"
    hash = "sha256-ZBjoG7ZOuTEmjaXPP9txAvjAjC46DeaLs0zrNzi8EQw="
  [mod."golang.org/x/net"]
    version = "v0.33.0"
    hash = "sha256-9swkU9vp6IflUUqAzK+y8PytSmrKLuryidP3RmRfe0w="
  [mod."golang.org/x/sync"]
    version = "v0.10.0"
    hash = "sha256-HWruKClrdoBKVdxKCyoazxeQV4dIYLdkHekQvx275/o="
  [mod."golang.org/x/sys"]
    version = "v0.28.0"
    hash = "sha256-kzSlDo5FKsQU9cLefIt2dueGUfz9XuEW+mGSGlPATGc="
  [mod."golang.org/x/text"]
    version = "v0.21.0"
    hash = "sha256-QaMwddBRnoS2mv9Y86eVC2x2wx/GZ7kr2zAJvwDeCPc="
  [mod."golang.org/x/time"]
    version = "v0.5.0"
    hash = "sha256-W6RgwgdYTO3byIPOFxrP2IpAZdgaGowAaVfYby7AULU="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20241209162323-e6fa225c2576"
    hash = "sha256-BE1xUsMUOYJLYuPm0AZtU5VxMTYgw0wyk7c+sDRsl+Q="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20241209162323-e6fa225c2576"
    hash = "sha256-wvRP+fvN4ydioW/Lt0zLVOKXMtEsryUdIGn/eGnJ5fE="
  [mod."google.golang.org/grpc"]
    version = "v1.68.1"
    hash = "sha256-WDHDk78qSd29gD01kQxTXgNUQ9ZJV+Wh7j8zz1qXHl0="
  [mod."google.golang.org/protobuf"]
    version = "v1.35.2"
    hash = "sha256-kS8fLAUgGNFn/nuIv/KUzJktRYK/nzpuJYwqzDIc7b8="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."modernc.org/gc/v3"]
    version = "v3.0.0-20241004144649-1aea3fae8852"
    hash = "sha256-nwh2xVgoeq97cSzcOQShyraromxAkYa0vCym8LqRQG4="
