schema = 3

[mod]
  [mod."github.com/MicahParks/jwkset"]
    version = "v0.9.6"
    hash = "sha256-9qBanINBkgJgex/fh3F6XQxr2k0hQa0/A4erzz7uDOU="
  [mod."github.com/MicahParks/keyfunc/v3"]
    version = "v3.6.1"
    hash = "sha256-7gtbvgRVONXZ/J9tDU63vuHSM2tXts9dunvb63gfhpI="
  [mod."github.com/a-h/templ"]
    version = "v0.3.937"
    hash = "sha256-JS/9MbOdMB44UOianP8GE0cg25wXn2NxCMKstw7pj6Y="
  [mod."github.com/cenkalti/backoff/v5"]
    version = "v5.0.3"
    hash = "sha256-bKq43PPD8RM6e7HePxHaO27traqm76bkvHcTVTQ+jeY="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/deckarep/golang-set/v2"]
    version = "v2.8.0"
    hash = "sha256-9f8aAodhyBeB3xPQKZTlcy3jGpLsY8fDwT2a+Xel0xg="
  [mod."github.com/dgryski/go-rendezvous"]
    version = "v0.0.0-20200823014737-9f7001d12a5f"
    hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="
  [mod."github.com/ebitengine/purego"]
    version = "v0.8.4"
    hash = "sha256-cMdZ3DhlGGldRsHRxkslAEwKgQnlbUMvDpt3boplxWs="
  [mod."github.com/exaring/otelpgx"]
    version = "v0.9.3"
    hash = "sha256-SqdhZqRIoj30cS5t1z2ZLq1IBAnfKRHNWZTuTod7aog="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.9"
    hash = "sha256-75uELLqb01djHTe7KdXvUidBK7SuejarYouEUuxaj8Q="
  [mod."github.com/go-jose/go-jose/v3"]
    version = "v3.0.4"
    hash = "sha256-RrLHCu9l6k0XVobdZQJ9Sx/VTQcWjrdLR5BEG7yXTEQ="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.3.0"
    hash = "sha256-tF8t3VcV71jQ4jbPL91BwR59AKDpUAFV1waIKzkXJu8="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.27.0"
    hash = "sha256-S6RXBwCOaLUumtS1xucTzOPGxA9XuA3R8RNdGE7w2Qc="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.1"
    hash = "sha256-ixcJ2RrK1ZH3YWGQZF9QFBo02NOuLeSp9wJ7gniipgY="
  [mod."github.com/gobwas/httphead"]
    version = "v0.1.0"
    hash = "sha256-6wFni/JkK2GqtVs3IW+GxHRNoSu4EJfzaBRGX2hF1IA="
  [mod."github.com/gobwas/pool"]
    version = "v0.2.1"
    hash = "sha256-py8/+Wo5Q83EbYMUKK5U/4scRcyMo2MjOoxqi5y+sUY="
  [mod."github.com/gobwas/ws"]
    version = "v1.4.0"
    hash = "sha256-I3BWBluCakfFuTKkwi5Dh+DlzpdcizOAxa4lKOUo8Ak="
  [mod."github.com/golang-jwt/jwt/v5"]
    version = "v5.3.0"
    hash = "sha256-VdN9Eo74ncMFJEVUSiJ1VRPMbC09FdVGno8wAReseXU="
  [mod."github.com/google/go-cmp"]
    version = "v0.7.0"
    hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.27.1"
    hash = "sha256-VjFHIgYwjpTY6Dy22XBVtNsfWMVoK3ZlvgRRN9llGWI="
  [mod."github.com/invopop/ctxi18n"]
    version = "v0.9.0"
    hash = "sha256-Qhyim2NQC/ofcpxN+cIookNwQahclhNld86VN/uDemw="
  [mod."github.com/invopop/yaml"]
    version = "v0.3.1"
    hash = "sha256-7x9sX9nc0ZL1+Fqh6hX+9ALNPXlIeCCkhGnwHR1VW0c="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.5"
    hash = "sha256-+bzuXlJnsvNEGjuhHIiZwmWepEmwj3Fl1ktLD50IKlU="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."github.com/leodido/go-urn"]
    version = "v1.4.0"
    hash = "sha256-Q6kplWkY37Tzy6GOme3Wut40jFK4Izun+ij/BJvcEu0="
  [mod."github.com/lmittmann/tint"]
    version = "v1.1.2"
    hash = "sha256-Jgt9Z4Wcast3DUQWVGJZwWd9zKWY6uQ7hfqKqad1Wr4="
  [mod."github.com/lufia/plan9stats"]
    version = "v0.0.0-20250317134145-8bc96cf8fc35"
    hash = "sha256-Ds6e5HDwEQURCnejUpZ/rxXWKDbgJ9UXRAtTHymV754="
  [mod."github.com/mdobak/go-xerrors"]
    version = "v1.0.0"
    hash = "sha256-/MFvLX56dfgWeuHJyKnwVspAQTRHs084kqHIZI7k9C8="
  [mod."github.com/mfridman/interpolate"]
    version = "v0.0.2"
    hash = "sha256-3u04CYOy7PLMctdkum5pltSTkYya8EfXJexbW7j0KB8="
  [mod."github.com/playwright-community/playwright-go"]
    version = "v0.5200.0"
    hash = "sha256-nQezkrv6fCEHlWl1VXqKT9gMPzd2j1fMnQ4j4INeHdI="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/power-devops/perfstat"]
    version = "v0.0.0-20240221224432-82ca36839d55"
    hash = "sha256-ujzuJ1ttQgjHQJEij4O/2+I8DZaUVZQCQgA4ysfqulI="
  [mod."github.com/pressly/goose/v3"]
    version = "v3.24.3"
    hash = "sha256-kBcchMFba8ow5GI5xTZfrjAy+N1418jmepfnGrbi7U8="
  [mod."github.com/redis/go-redis/extra/rediscmd/v9"]
    version = "v9.12.1"
    hash = "sha256-CvHtXtDAIcDpZT5YGodILF7sTosI1+U4RlPuHyCAq2s="
  [mod."github.com/redis/go-redis/extra/redisotel/v9"]
    version = "v9.12.1"
    hash = "sha256-JEKY5emgwG9NLf0qUfRVhQlfEPFW2B0p6HJE2fTSSG4="
  [mod."github.com/redis/go-redis/v9"]
    version = "v9.12.1"
    hash = "sha256-MHwOv3RaZ5Bq/pOL/hXd0kErXQeo1NwdCpRtRD6De1U="
  [mod."github.com/samber/lo"]
    version = "v1.51.0"
    hash = "sha256-Vgixn+tB/Rb8G2NTS3PuZO7iaXvmZtMaSvLETJhWIWM="
  [mod."github.com/samber/slog-common"]
    version = "v0.19.0"
    hash = "sha256-OYXVbZML7c3mFClVy8GEnNoWW+4OfcBsxWDtKh1u7B8="
  [mod."github.com/samber/slog-multi"]
    version = "v1.4.1"
    hash = "sha256-ggMyUs+rt06Q0pJGFd8G0hFEeRH6jczX0v07fMfLqNM="
  [mod."github.com/sethvargo/go-envconfig"]
    version = "v1.3.0"
    hash = "sha256-Kb7CtqaURgv/qt1BlliqSc7k7aVtWG/KWLtUcuRfFx0="
  [mod."github.com/sethvargo/go-retry"]
    version = "v0.3.0"
    hash = "sha256-1ZnFRHAaQjralGKVRoCbiwCXXB3w4kS3f+2hK9S8lbU="
  [mod."github.com/shirou/gopsutil/v4"]
    version = "v4.25.7"
    hash = "sha256-4uHSABtC2kBpHRSGmg00NGUuNTczCn8qKXR36ValJpU="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.2"
    hash = "sha256-VKYxrrFb1nkX6Wu3tE5DoP9+fCttwSl9pgLN6567nck="
  [mod."github.com/stretchr/testify"]
    version = "v1.10.0"
    hash = "sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI="
  [mod."github.com/tklauser/go-sysconf"]
    version = "v0.3.15"
    hash = "sha256-Twh9dD/mfNb7Qr5p/KmaK5Xi25VJwj5jESZeJr0qeUc="
  [mod."github.com/tklauser/numcpus"]
    version = "v0.10.0"
    hash = "sha256-NWg68H2Y6MijtlscPaZlLQwgPthEwLV+WpRT01m6kkI="
  [mod."github.com/veqryn/slog-context"]
    version = "v0.8.0"
    hash = "sha256-fCPH3iKgl8KNDvx0IyP4BJXXGtIDjoqOGfWf+Zodlso="
  [mod."github.com/vgarvardt/pgx-google-uuid/v5"]
    version = "v5.6.0"
    hash = "sha256-F+E8rFEHnmJKcCxl4hA3MosSEKqxytp5y7VMVZLFQEg="
  [mod."github.com/yuin/goldmark"]
    version = "v1.7.13"
    hash = "sha256-vBCxZrPYPc8x/nvAAv3Au59dCCyfS80Vw3/a9EXK7TE="
  [mod."github.com/yusufpapurcu/wmi"]
    version = "v1.2.4"
    hash = "sha256-N+YDBjOW59YOsZ2lRBVtFsEEi48KhNQRb63/0ZSU3bA="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.1.0"
    hash = "sha256-cA9qCCu8P1NSJRxgmpfkfa5rKyn9X+Y/9FSmSd5xjyo="
  [mod."go.opentelemetry.io/contrib/bridges/otelslog"]
    version = "v0.12.0"
    hash = "sha256-MCg/dq8ScRyW+AtOZddfn8CoY3L2p473W34iahBnXxQ="
  [mod."go.opentelemetry.io/contrib/instrumentation/host"]
    version = "v0.62.0"
    hash = "sha256-+aRcRCLdJZeb7QXw9AmDDa4oNCUG3RISiZhiq56i+5c="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.62.0"
    hash = "sha256-WcDogpsvFxGOVqc+/ljlZ10nrOU2q0rPteukGyWWmfc="
  [mod."go.opentelemetry.io/contrib/instrumentation/runtime"]
    version = "v0.62.0"
    hash = "sha256-iYn8QSYspvdmTWdjE4EjILKtX1G4pgKzIIPz0v/+qEM="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.37.0"
    hash = "sha256-zWpyp9K8/Te86uhNjamchZctTdAnmHhoVw9m4ACfSoo="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp"]
    version = "v1.37.0"
    hash = "sha256-ZJ8eSd4Yr44YfvgzO0Wmy5PONYQW9sN8qZBgVmukmV0="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.37.0"
    hash = "sha256-mvkSTeIX7Oli2/8iP4LP47X0Auab8BKi8FB0Rw668iE="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"]
    version = "v1.37.0"
    hash = "sha256-fF39F85C4Zcmwr1UJEz+h8Y173T66R/NTuJhymzp4/4="
  [mod."go.opentelemetry.io/otel/log"]
    version = "v0.13.0"
    hash = "sha256-KscPGnEJhNlNiqL+3ZCXNnKU6fHzEYgQVoVGev6RRBc="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.37.0"
    hash = "sha256-BWnkdldA3xzGhnaConzMAuQzOnugytIvrP6GjkZVAYg="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.37.0"
    hash = "sha256-uNFhKuSRhf+SXwVu8mg/qqsVio7KstVN/WyCTxgWHT0="
  [mod."go.opentelemetry.io/otel/sdk/metric"]
    version = "v1.37.0"
    hash = "sha256-dm6Aa5UDFgQCVexayiWu85A1ir1lpNn5rIN9tj9KVDs="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.37.0"
    hash = "sha256-FBeLOb5qmIiE9VmbgCf1l/xpndBqHkRiaPt1PvoKrVY="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.7.1"
    hash = "sha256-5VjS+8TB2E4qIsq/U5myaCDokQtQcBebMuOMp6/DIRE="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."golang.org/x/crypto"]
    version = "v0.41.0"
    hash = "sha256-o5Di0lsFmYnXl7a5MBTqmN9vXMCRpE9ay71C1Ar8jEY="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20250813145105-42675adae3e6"
    hash = "sha256-XI3PzI5kiJO09twj6aT98jyggZRxcpo3SfYfHOIhA0w="
  [mod."golang.org/x/net"]
    version = "v0.43.0"
    hash = "sha256-bf3iQFrsC8BoarVaS0uSspEFAcr1zHp1uziTtBpwV34="
  [mod."golang.org/x/sync"]
    version = "v0.16.0"
    hash = "sha256-sqKDRESeMzLe0jWGWltLZL/JIgrn0XaIeBWCzVN3Bks="
  [mod."golang.org/x/sys"]
    version = "v0.35.0"
    hash = "sha256-ZKM8pesQE6NAFZeKQ84oPn5JMhGr8g4TSwLYAsHMGSI="
  [mod."golang.org/x/text"]
    version = "v0.28.0"
    hash = "sha256-8UlJniGK+km4Hmrw6XMxELnExgrih7+z8tU26Cntmto="
  [mod."golang.org/x/time"]
    version = "v0.12.0"
    hash = "sha256-Cp3oxrCMH2wyxjzr5SHVmyhgaoUuSl56Uy00Q7DYEpw="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20250811230008-5f3141c8851a"
    hash = "sha256-a/45jDw8clwYg8b+FqG+x/1BNk2GjK18KIJbG3yApSo="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20250811230008-5f3141c8851a"
    hash = "sha256-hbGMdlN/vwPIOJhYv6CAEnpQqTXbQ1GlXabiQUOv3sc="
  [mod."google.golang.org/grpc"]
    version = "v1.74.2"
    hash = "sha256-tvYMdfu/ZQZRPZNmnQI4CZpg46CM8+mD49hw0gFheGs="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.7"
    hash = "sha256-6xCU+t2AVPcscMKenVs4etGqutYGPDXCQ3DCD3PpTq4="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
