schema = 3

[mod]
  [mod."github.com/MicahParks/jwkset"]
    version = "v0.9.6"
    hash = "sha256-9qBanINBkgJgex/fh3F6XQxr2k0hQa0/A4erzz7uDOU="
  [mod."github.com/MicahParks/keyfunc/v3"]
    version = "v3.6.1"
    hash = "sha256-7gtbvgRVONXZ/J9tDU63vuHSM2tXts9dunvb63gfhpI="
  [mod."github.com/a-h/templ"]
    version = "v0.3.943"
    hash = "sha256-1lqdcz0q13m8rNKFXp84kP69q8c5WHXNGhUklK6XUDk="
  [mod."github.com/cenkalti/backoff/v5"]
    version = "v5.0.3"
    hash = "sha256-bKq43PPD8RM6e7HePxHaO27traqm76bkvHcTVTQ+jeY="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/deckarep/golang-set/v2"]
    version = "v2.8.0"
    hash = "sha256-9f8aAodhyBeB3xPQKZTlcy3jGpLsY8fDwT2a+Xel0xg="
  [mod."github.com/dgryski/go-rendezvous"]
    version = "v0.0.0-20200823014737-9f7001d12a5f"
    hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="
  [mod."github.com/ebitengine/purego"]
    version = "v0.8.4"
    hash = "sha256-cMdZ3DhlGGldRsHRxkslAEwKgQnlbUMvDpt3boplxWs="
  [mod."github.com/exaring/otelpgx"]
    version = "v0.9.3"
    hash = "sha256-SqdhZqRIoj30cS5t1z2ZLq1IBAnfKRHNWZTuTod7aog="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.10"
    hash = "sha256-ha8NJOAWcmEfQaybfNxyUupt0+zlWxoAKLjCacew43s="
  [mod."github.com/getsentry/sentry-go"]
    version = "v0.35.1"
    hash = "sha256-dfCaMRLn+I7Yd8cm2W8YQOWQlFStK7Tpnf/WvglNQ0E="
  [mod."github.com/go-jose/go-jose/v3"]
    version = "v3.0.4"
    hash = "sha256-RrLHCu9l6k0XVobdZQJ9Sx/VTQcWjrdLR5BEG7yXTEQ="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.3.0"
    hash = "sha256-tF8t3VcV71jQ4jbPL91BwR59AKDpUAFV1waIKzkXJu8="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.27.0"
    hash = "sha256-S6RXBwCOaLUumtS1xucTzOPGxA9XuA3R8RNdGE7w2Qc="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.1"
    hash = "sha256-ixcJ2RrK1ZH3YWGQZF9QFBo02NOuLeSp9wJ7gniipgY="
  [mod."github.com/gobwas/httphead"]
    version = "v0.1.0"
    hash = "sha256-6wFni/JkK2GqtVs3IW+GxHRNoSu4EJfzaBRGX2hF1IA="
  [mod."github.com/gobwas/pool"]
    version = "v0.2.1"
    hash = "sha256-py8/+Wo5Q83EbYMUKK5U/4scRcyMo2MjOoxqi5y+sUY="
  [mod."github.com/gobwas/ws"]
    version = "v1.4.0"
    hash = "sha256-I3BWBluCakfFuTKkwi5Dh+DlzpdcizOAxa4lKOUo8Ak="
  [mod."github.com/gofrs/uuid/v5"]
    version = "v5.3.2"
    hash = "sha256-kQOJpGIw+pIwKkaDMNxmzu39ETHunvR0pV8rSPY9NIM="
  [mod."github.com/golang-jwt/jwt/v5"]
    version = "v5.3.0"
    hash = "sha256-VdN9Eo74ncMFJEVUSiJ1VRPMbC09FdVGno8wAReseXU="
  [mod."github.com/google/go-cmp"]
    version = "v0.7.0"
    hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.27.2"
    hash = "sha256-DVhStnXW+zJ2HUpdNUl2GU0Nkv6xN80gLiDXdxz5gwQ="
  [mod."github.com/invopop/ctxi18n"]
    version = "v0.9.0"
    hash = "sha256-Qhyim2NQC/ofcpxN+cIookNwQahclhNld86VN/uDemw="
  [mod."github.com/invopop/yaml"]
    version = "v0.3.1"
    hash = "sha256-7x9sX9nc0ZL1+Fqh6hX+9ALNPXlIeCCkhGnwHR1VW0c="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.5"
    hash = "sha256-+bzuXlJnsvNEGjuhHIiZwmWepEmwj3Fl1ktLD50IKlU="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."github.com/leodido/go-urn"]
    version = "v1.4.0"
    hash = "sha256-Q6kplWkY37Tzy6GOme3Wut40jFK4Izun+ij/BJvcEu0="
  [mod."github.com/lmittmann/tint"]
    version = "v1.1.2"
    hash = "sha256-Jgt9Z4Wcast3DUQWVGJZwWd9zKWY6uQ7hfqKqad1Wr4="
  [mod."github.com/lufia/plan9stats"]
    version = "v0.0.0-20250827001030-24949be3fa54"
    hash = "sha256-ln7SyNSDeJcg0IaOYm6FQQ2Vr6mEvDbuoBc6iaxYIvs="
  [mod."github.com/mdobak/go-xerrors"]
    version = "v1.0.0"
    hash = "sha256-/MFvLX56dfgWeuHJyKnwVspAQTRHs084kqHIZI7k9C8="
  [mod."github.com/mfridman/interpolate"]
    version = "v0.0.2"
    hash = "sha256-3u04CYOy7PLMctdkum5pltSTkYya8EfXJexbW7j0KB8="
  [mod."github.com/playwright-community/playwright-go"]
    version = "v0.5200.0"
    hash = "sha256-nQezkrv6fCEHlWl1VXqKT9gMPzd2j1fMnQ4j4INeHdI="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/power-devops/perfstat"]
    version = "v0.0.0-20240221224432-82ca36839d55"
    hash = "sha256-ujzuJ1ttQgjHQJEij4O/2+I8DZaUVZQCQgA4ysfqulI="
  [mod."github.com/pressly/goose/v3"]
    version = "v3.24.3"
    hash = "sha256-kBcchMFba8ow5GI5xTZfrjAy+N1418jmepfnGrbi7U8="
  [mod."github.com/redis/go-redis/extra/rediscmd/v9"]
    version = "v9.13.0"
    hash = "sha256-CLu1qqXPiHc/C/XkqCqU0TXbC3M2Lqi/hN2nDB1qvSI="
  [mod."github.com/redis/go-redis/extra/redisotel/v9"]
    version = "v9.13.0"
    hash = "sha256-hDBTf7ylde1FnnzpkyT/V6n5kqDwWHDpwvRNbC5m5YM="
  [mod."github.com/redis/go-redis/v9"]
    version = "v9.13.0"
    hash = "sha256-1y1fT+leOHZpKABVGk+fw3Wt/AHMNWvfY0Cr5/3zhuY="
  [mod."github.com/samber/lo"]
    version = "v1.51.0"
    hash = "sha256-Vgixn+tB/Rb8G2NTS3PuZO7iaXvmZtMaSvLETJhWIWM="
  [mod."github.com/samber/slog-common"]
    version = "v0.19.0"
    hash = "sha256-OYXVbZML7c3mFClVy8GEnNoWW+4OfcBsxWDtKh1u7B8="
  [mod."github.com/samber/slog-multi"]
    version = "v1.4.1"
    hash = "sha256-ggMyUs+rt06Q0pJGFd8G0hFEeRH6jczX0v07fMfLqNM="
  [mod."github.com/sethvargo/go-envconfig"]
    version = "v1.3.0"
    hash = "sha256-Kb7CtqaURgv/qt1BlliqSc7k7aVtWG/KWLtUcuRfFx0="
  [mod."github.com/sethvargo/go-retry"]
    version = "v0.3.0"
    hash = "sha256-1ZnFRHAaQjralGKVRoCbiwCXXB3w4kS3f+2hK9S8lbU="
  [mod."github.com/shirou/gopsutil/v4"]
    version = "v4.25.8"
    hash = "sha256-dHPZ+S6nLlGyUzcJt+x89WdxFZ7KKm5LACXF5/7OLsM="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.2"
    hash = "sha256-VKYxrrFb1nkX6Wu3tE5DoP9+fCttwSl9pgLN6567nck="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/tklauser/go-sysconf"]
    version = "v0.3.15"
    hash = "sha256-Twh9dD/mfNb7Qr5p/KmaK5Xi25VJwj5jESZeJr0qeUc="
  [mod."github.com/tklauser/numcpus"]
    version = "v0.10.0"
    hash = "sha256-NWg68H2Y6MijtlscPaZlLQwgPthEwLV+WpRT01m6kkI="
  [mod."github.com/veqryn/slog-context"]
    version = "v0.8.0"
    hash = "sha256-fCPH3iKgl8KNDvx0IyP4BJXXGtIDjoqOGfWf+Zodlso="
  [mod."github.com/vgarvardt/pgx-google-uuid/v5"]
    version = "v5.6.0"
    hash = "sha256-F+E8rFEHnmJKcCxl4hA3MosSEKqxytp5y7VMVZLFQEg="
  [mod."github.com/yuin/goldmark"]
    version = "v1.7.13"
    hash = "sha256-vBCxZrPYPc8x/nvAAv3Au59dCCyfS80Vw3/a9EXK7TE="
  [mod."github.com/yusufpapurcu/wmi"]
    version = "v1.2.4"
    hash = "sha256-N+YDBjOW59YOsZ2lRBVtFsEEi48KhNQRb63/0ZSU3bA="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.1.0"
    hash = "sha256-cA9qCCu8P1NSJRxgmpfkfa5rKyn9X+Y/9FSmSd5xjyo="
  [mod."go.opentelemetry.io/contrib/bridges/otelslog"]
    version = "v0.13.0"
    hash = "sha256-UECL7pBdtsT3iafHTG+yFc2mptqwV+IgnDVVSJeTiw8="
  [mod."go.opentelemetry.io/contrib/instrumentation/host"]
    version = "v0.63.0"
    hash = "sha256-hQ04HwaLrpQMjqYQimFow+jhHan7CInvm3FLODLJNho="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.63.0"
    hash = "sha256-kDRjKy2nJut38dHZbZy+haqSAh8qFgtTMqfe4y2WhCA="
  [mod."go.opentelemetry.io/contrib/instrumentation/runtime"]
    version = "v0.63.0"
    hash = "sha256-yvd32st0gspwDpLGEL3m9cbw3qk48F9zt8B7aSxZH80="
  [mod."go.opentelemetry.io/contrib/processors/minsev"]
    version = "v0.11.0"
    hash = "sha256-lMjE1fIp3UC9KB2jZZ0/akIq9OIipZnM0ShknJAH4Jg="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.38.0"
    hash = "sha256-OU4EVEGwbopbYZLDBfAelR/4yjzfV+UVp4UFt3UvkOE="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp"]
    version = "v0.14.0"
    hash = "sha256-nsUAPk/kn1qzxlcRmie0HCo68sWpFlmnATd3Kq/pSb8="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp"]
    version = "v1.38.0"
    hash = "sha256-kz7NykL1xLHfyl1OYZg/6Ted5JHWaTTaBl/zisU9BQE="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.38.0"
    hash = "sha256-erOjiMK86nZaiKKo2DSpqEUBh8Y+PobuCxCTq7Bj2LM="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"]
    version = "v1.38.0"
    hash = "sha256-R0rlOcR1pMfCYKOLcvwVw1UlcEf+gtK+MOlo+fHWIRQ="
  [mod."go.opentelemetry.io/otel/log"]
    version = "v0.14.0"
    hash = "sha256-fVKuFX4/O7RW1CnNLPhHc21FGJxXBZTCr+LBQ1JEl7s="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.38.0"
    hash = "sha256-5W6Yd9nl/eyvL29e9hSfosISpxfSQcBAwkqI4htHWCg="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.38.0"
    hash = "sha256-Qxqf7LEbS8Znp8qeQPbgm0jeFVhZNwV2d5zuKysIKIQ="
  [mod."go.opentelemetry.io/otel/sdk/log"]
    version = "v0.14.0"
    hash = "sha256-/D8QOFQjLZcC0uUesclVA6SAarFswisFoxgWqiNKqr0="
  [mod."go.opentelemetry.io/otel/sdk/metric"]
    version = "v1.38.0"
    hash = "sha256-Nahjgwhfx9NOJaM87fVpNFgzMOtJYPMehXKCswV59vI="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.38.0"
    hash = "sha256-gNXUPmsPAw6JVH3YT/xwmRpn5QoDxyzc9kLe/5ldo0o="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.8.0"
    hash = "sha256-0Gn4MNxfbgv7zNxFyci6WaTeQA0ynMyXWKrIEEhN//o="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."golang.org/x/crypto"]
    version = "v0.41.0"
    hash = "sha256-o5Di0lsFmYnXl7a5MBTqmN9vXMCRpE9ay71C1Ar8jEY="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20250819193227-8b4c13bb791b"
    hash = "sha256-rp8WHdfnVSbFi4ENtReQ0qLzfXlUHuC58cwtKqEbwG8="
  [mod."golang.org/x/net"]
    version = "v0.43.0"
    hash = "sha256-bf3iQFrsC8BoarVaS0uSspEFAcr1zHp1uziTtBpwV34="
  [mod."golang.org/x/sync"]
    version = "v0.16.0"
    hash = "sha256-sqKDRESeMzLe0jWGWltLZL/JIgrn0XaIeBWCzVN3Bks="
  [mod."golang.org/x/sys"]
    version = "v0.35.0"
    hash = "sha256-ZKM8pesQE6NAFZeKQ84oPn5JMhGr8g4TSwLYAsHMGSI="
  [mod."golang.org/x/text"]
    version = "v0.28.0"
    hash = "sha256-8UlJniGK+km4Hmrw6XMxELnExgrih7+z8tU26Cntmto="
  [mod."golang.org/x/time"]
    version = "v0.12.0"
    hash = "sha256-Cp3oxrCMH2wyxjzr5SHVmyhgaoUuSl56Uy00Q7DYEpw="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20250826171959-ef028d996bc1"
    hash = "sha256-jTPospegY+TRve8qiJJh+n19JHwxfY7iJ16BGUWd+Bw="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20250826171959-ef028d996bc1"
    hash = "sha256-kV8cgw4mlIzyZJDwrFYVpmBuuU3RhPKCwmJdIP9z62M="
  [mod."google.golang.org/grpc"]
    version = "v1.75.0"
    hash = "sha256-bMJEB2luUeYWwsQWqzuq4Wro2tTKBWGJPuTtzioJcfM="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.8"
    hash = "sha256-yZN8ZON0b5HjUNUSubHst7zbvnMsOzd81tDPYQRtPgM="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
