schema = 3

[mod]
  [mod."github.com/a-h/templ"]
    version = "v0.2.778"
    hash = "sha256-54iSeNJU4dMMkxHEh0KyRu//vADMnt93fjmXzqc2xPE="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/deckarep/golang-set/v2"]
    version = "v2.6.0"
    hash = "sha256-ni1XK75Q8iBBmxgoyZTedP4RmrUPzFC4978xB4HKdfs="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/fatih/color"]
    version = "v1.18.0"
    hash = "sha256-pP5y72FSbi4j/BjyVq/XbAOFjzNjMxZt2R/lFFxGWvY="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/flexstack/uuid"]
    version = "v1.0.0"
    hash = "sha256-HvQMtZCvBo6txJVBSddItq+n2jqlJwUa29RanNWXWnU="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.6"
    hash = "sha256-W/uPcE22Fduw1XmX8Ujf1S9SYVOcEoE1wzK4I0/vapw="
  [mod."github.com/go-jose/go-jose/v3"]
    version = "v3.0.3"
    hash = "sha256-PsjN1vVhAFI6X11iIkpQU4i7Ax6FvkhXNxApeBa2BvA="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.2"
    hash = "sha256-/W6qGilFlZNTb9Uq48xGZ4IbsVeSwJiAMLw4wiNYHLI="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.1"
    hash = "sha256-ixcJ2RrK1ZH3YWGQZF9QFBo02NOuLeSp9wJ7gniipgY="
  [mod."github.com/gobwas/httphead"]
    version = "v0.1.0"
    hash = "sha256-6wFni/JkK2GqtVs3IW+GxHRNoSu4EJfzaBRGX2hF1IA="
  [mod."github.com/gobwas/pool"]
    version = "v0.2.1"
    hash = "sha256-py8/+Wo5Q83EbYMUKK5U/4scRcyMo2MjOoxqi5y+sUY="
  [mod."github.com/gobwas/ws"]
    version = "v1.4.0"
    hash = "sha256-I3BWBluCakfFuTKkwi5Dh+DlzpdcizOAxa4lKOUo8Ak="
  [mod."github.com/gomig/avatar"]
    version = "v1.0.3"
    hash = "sha256-6L2wF8eAdp8bChCMkP0KIgxHm/ak1mnNtrt2FUQm1Pc="
  [mod."github.com/gomig/utils"]
    version = "v1.0.1"
    hash = "sha256-jOQKphQVuLEuKsMY7s2sj8CPYFkQUs7o8uYELo7s4LQ="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/hashicorp/golang-lru/v2"]
    version = "v2.0.7"
    hash = "sha256-t1bcXLgrQNOYUVyYEZ0knxcXpsTk4IuJZDjKvyJX75g="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.9"
    hash = "sha256-FxHk4OuwsbiH1OLI+Q0oA4KpcOB786sEfik0G+GNoow="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mfridman/interpolate"]
    version = "v0.0.2"
    hash = "sha256-3u04CYOy7PLMctdkum5pltSTkYya8EfXJexbW7j0KB8="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/muesli/go-app-paths"]
    version = "v0.2.2"
    hash = "sha256-yfARJSu1IP64LwXW9ELzYB+Ex5Q5QFDWtKChh/1356U="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/ncruces/go-strftime"]
    version = "v0.1.9"
    hash = "sha256-T0iw+UEckzueWHT88PkTnZZixyKCEa+DTLzIiiohuWY="
  [mod."github.com/playwright-community/playwright-go"]
    version = "v0.4702.0"
    hash = "sha256-HN2/yB2SFceEeVCWNthKaPQ4p1VsD6Kh72tTefFmMPU="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/pressly/goose/v3"]
    version = "v3.22.1"
    hash = "sha256-ibCYmKkhW1sEagYunBwSqQG9i1ZonkkGSPWRz7okfks="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.20.5"
    hash = "sha256-RbDZTBH+j2ZNLbHSMFxW0j8UStvkwc4IHTz3My9w4qo="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.1"
    hash = "sha256-rIDyUzNfxRA934PIoySR0EhuBbZVRK/25Jlc/r8WODw="
  [mod."github.com/prometheus/common"]
    version = "v0.60.0"
    hash = "sha256-olykcW7bZOWAH8VrYqP+8Tf5a+0kfiHcT2QF492j2KI="
  [mod."github.com/prometheus/procfs"]
    version = "v0.15.1"
    hash = "sha256-H+WXJemFFwdoglmD6p7JRjrJJZmIVAmJwYmLbZ8Q9sw="
  [mod."github.com/remyoudompheng/bigfft"]
    version = "v0.0.0-20230129092748-24d4a6f8daec"
    hash = "sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.13.1"
    hash = "sha256-fD4n3XVDNHL7hfUXK9qi31LpBVzWnRK/7LNc3BmPtnU="
  [mod."github.com/sethvargo/go-envconfig"]
    version = "v1.1.0"
    hash = "sha256-WelRHfyZG9hrA4fbQcfBawb2ZXBQNT1ourEYHzQdZ4w="
  [mod."github.com/sethvargo/go-retry"]
    version = "v0.3.0"
    hash = "sha256-1ZnFRHAaQjralGKVRoCbiwCXXB3w4kS3f+2hK9S8lbU="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.2"
    hash = "sha256-VKYxrrFb1nkX6Wu3tE5DoP9+fCttwSl9pgLN6567nck="
  [mod."github.com/stretchr/testify"]
    version = "v1.9.0"
    hash = "sha256-uUp/On+1nK+lARkTVtb5RxlW15zxtw2kaAFuIASA+J0="
  [mod."github.com/veqryn/slog-context"]
    version = "v0.7.0"
    hash = "sha256-eCdqk/nS9o/Zsgi2q9425dRyrXCWKHNS8VG1hI352mU="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.56.0"
    hash = "sha256-Nw9uF/TUoFnH0488VNHVndgoSX+lxZy1Y93Wryl7qP4="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.31.0"
    hash = "sha256-NQBHyMSRn9vaxSrNHYwv0oX1aJuEpyks/gpYEWHlx6k="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.31.0"
    hash = "sha256-nyu/pH2yjmc5zUD/ufdPtrDnoBNUZ+lq6iXQPy5EZ0k="
  [mod."go.opentelemetry.io/otel/exporters/prometheus"]
    version = "v0.53.0"
    hash = "sha256-ig9hJ/Elr9PvDqlE/yoboWu/UsjzVSKAnjmvs6uaiMA="
  [mod."go.opentelemetry.io/otel/exporters/stdout/stdouttrace"]
    version = "v1.31.0"
    hash = "sha256-O+X4ja/5GWGsWjvTJafZkfzjEc6OA2jBDOzi9uq97Mw="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.31.0"
    hash = "sha256-2s5IN8IwPBitqnjIEraOfg8fWd3nIy8jWoKTXa+uUs4="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.31.0"
    hash = "sha256-fFnX/qTdVn6x+Kj6mGZZGSD4MGsqAiPNQWuM6S+VZmQ="
  [mod."go.opentelemetry.io/otel/sdk/metric"]
    version = "v1.31.0"
    hash = "sha256-rqjFPHV6hJ9NUgca4eI9fSBsLS1Dm4TKz3BZpAdVFO4="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.31.0"
    hash = "sha256-iVDe3qNzmX1+MQTAoaeIbhnIbu/hnx4OsUIPlxuX1gY="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.3.1"
    hash = "sha256-WaXW64jWowTDlNYDHiGKmHzRUrwJ8Rkymyvz7W6UHd8="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20241009180824-f66d83c29e7c"
    hash = "sha256-ICL1UU2rrOBespsjNrlvrAhZOFLMcxYWAx8pDQCgAXM="
  [mod."golang.org/x/net"]
    version = "v0.30.0"
    hash = "sha256-i1f6wJHfFq0nKtbuY7twZ7uPyUbRYHVjd3uy0SS06mU="
  [mod."golang.org/x/sync"]
    version = "v0.8.0"
    hash = "sha256-usvF0z7gq1vsX58p4orX+8WHlv52pdXgaueXlwj2Wss="
  [mod."golang.org/x/sys"]
    version = "v0.26.0"
    hash = "sha256-YjklsWNhx4g4TaWRWfFe1TMFKujbqiaNvZ38bfI35fM="
  [mod."golang.org/x/text"]
    version = "v0.19.0"
    hash = "sha256-C92pSYLLUQ2NKKcc60wpoSJ5UWAfnWkmd997C13fXdU="
  [mod."google.golang.org/protobuf"]
    version = "v1.35.1"
    hash = "sha256-4NtUQoBvlPGFGjo7c+E1EBS/sb8oy50MGy45KGWPpWo="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."modernc.org/gc/v3"]
    version = "v3.0.0-20241004144649-1aea3fae8852"
    hash = "sha256-nwh2xVgoeq97cSzcOQShyraromxAkYa0vCym8LqRQG4="
  [mod."modernc.org/libc"]
    version = "v1.61.0"
    hash = "sha256-w3mZHUqOI1XTUXj3QkCg+8z1ivbxBmoSU39DXOCAIXU="
  [mod."modernc.org/mathutil"]
    version = "v1.6.0"
    hash = "sha256-lfuEiS1odd2TWrTylnaGihSJ9myqKs3FLdpvd7PqTnE="
  [mod."modernc.org/memory"]
    version = "v1.8.0"
    hash = "sha256-ucvPr73zg8LjvU+bcoIPKTgwgcon3U9VhKrLEMH81xg="
  [mod."modernc.org/sqlite"]
    version = "v1.33.1"
    hash = "sha256-Bhk9RNeHjgMIHt8n6L6cLxY2mMMAp4Wik5KR0954GaA="
  [mod."modernc.org/strutil"]
    version = "v1.2.0"
    hash = "sha256-NTYIWMRZjHmR77LMvsFOMCitt7toKTfH+zChYAMzZ2Y="
  [mod."modernc.org/token"]
    version = "v1.1.0"
    hash = "sha256-m8WyXJ9Mdw6B43wmy2+3HE7zHEi9ocBrhwe/eq+zdu8="
