schema = 3

[mod]
  [mod."github.com/MicahParks/jwkset"]
    version = "v0.8.0"
    hash = "sha256-aAqbC/4s3bHZVTMzzcG4v9lhyQo5AV3S6lFRg1aUQCQ="
  [mod."github.com/MicahParks/keyfunc/v3"]
    version = "v3.3.10"
    hash = "sha256-G6gA2D+46hw9QZex3jF+4OBkaoc6GGu/OB0B73iQkVA="
  [mod."github.com/a-h/templ"]
    version = "v0.3.833"
    hash = "sha256-OSGAJDVPYqgb72DZXeemLp37aGrrxMt+PQNKW5voKQ0="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.3.0"
    hash = "sha256-wfVjNZsGG1WoNC5aL+kdcy6QXPgZo4THAevZ1787md8="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/deckarep/golang-set/v2"]
    version = "v2.7.0"
    hash = "sha256-2Znzm9izwgpaOQAJaFA1b2rBZ/VTt1vGYyxKVEzxMeY="
  [mod."github.com/dgryski/go-rendezvous"]
    version = "v0.0.0-20200823014737-9f7001d12a5f"
    hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="
  [mod."github.com/ebitengine/purego"]
    version = "v0.8.2"
    hash = "sha256-f3Q8KVX+RkHa1EsGF+U8E9MHHOCZ9j2jtMJOTPCZw08="
  [mod."github.com/exaring/otelpgx"]
    version = "v0.9.0"
    hash = "sha256-zSdSsbjxCFZ+2G6L7axT941haFLEd1Ufz1/ur8O8Z4Q="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.8"
    hash = "sha256-ElqfQtnoGHyVqtN0mJjeWakQ6N5x+nVaX3+uOV7Q5Xk="
  [mod."github.com/go-jose/go-jose/v3"]
    version = "v3.0.3"
    hash = "sha256-PsjN1vVhAFI6X11iIkpQU4i7Ax6FvkhXNxApeBa2BvA="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.2"
    hash = "sha256-/W6qGilFlZNTb9Uq48xGZ4IbsVeSwJiAMLw4wiNYHLI="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.3.0"
    hash = "sha256-tF8t3VcV71jQ4jbPL91BwR59AKDpUAFV1waIKzkXJu8="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.24.0"
    hash = "sha256-zaZtWTAcn1JncUOGVpLigfJW17wxOzJt9aLOs7mNjSM="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.1"
    hash = "sha256-ixcJ2RrK1ZH3YWGQZF9QFBo02NOuLeSp9wJ7gniipgY="
  [mod."github.com/gobwas/httphead"]
    version = "v0.1.0"
    hash = "sha256-6wFni/JkK2GqtVs3IW+GxHRNoSu4EJfzaBRGX2hF1IA="
  [mod."github.com/gobwas/pool"]
    version = "v0.2.1"
    hash = "sha256-py8/+Wo5Q83EbYMUKK5U/4scRcyMo2MjOoxqi5y+sUY="
  [mod."github.com/gobwas/ws"]
    version = "v1.4.0"
    hash = "sha256-I3BWBluCakfFuTKkwi5Dh+DlzpdcizOAxa4lKOUo8Ak="
  [mod."github.com/golang-jwt/jwt/v5"]
    version = "v5.2.1"
    hash = "sha256-3AMtL0kAD5L2/3eHf/Q6+hqga8mEaeEs+Hcdlx65go4="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.26.1"
    hash = "sha256-G3bEuU6hadbIel4VAIvukw3CDJfLAXDXztFEKWiwY3o="
  [mod."github.com/invopop/ctxi18n"]
    version = "v0.9.0"
    hash = "sha256-Qhyim2NQC/ofcpxN+cIookNwQahclhNld86VN/uDemw="
  [mod."github.com/invopop/yaml"]
    version = "v0.3.1"
    hash = "sha256-7x9sX9nc0ZL1+Fqh6hX+9ALNPXlIeCCkhGnwHR1VW0c="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.2"
    hash = "sha256-FEh0GwrkTlFPZiqT6m3jYg5OV62/LHs/otMQuJfcMNw="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."github.com/leodido/go-urn"]
    version = "v1.4.0"
    hash = "sha256-Q6kplWkY37Tzy6GOme3Wut40jFK4Izun+ij/BJvcEu0="
  [mod."github.com/lmittmann/tint"]
    version = "v1.0.7"
    hash = "sha256-/Pk4Qq3kKPBKRIjgnr6WM2bsvVoQM57DlDuZCQkR3Ds="
  [mod."github.com/lufia/plan9stats"]
    version = "v0.0.0-20240909124753-873cd0166683"
    hash = "sha256-/SDtTolLkCiDQnF22rRFCiHUdrz8ND37lCxLoOcVQKk="
  [mod."github.com/mdobak/go-xerrors"]
    version = "v0.3.1"
    hash = "sha256-/RkHFCPT8CoQtgy3FDu9JZwVFRH1fnPdMW5dbqVWqAM="
  [mod."github.com/mfridman/interpolate"]
    version = "v0.0.2"
    hash = "sha256-3u04CYOy7PLMctdkum5pltSTkYya8EfXJexbW7j0KB8="
  [mod."github.com/playwright-community/playwright-go"]
    version = "v0.4902.0"
    hash = "sha256-uEfQtfnr5YnVVFDBBl+tUeD3VFKnIkM6YUwJT40YXkY="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/power-devops/perfstat"]
    version = "v0.0.0-20240221224432-82ca36839d55"
    hash = "sha256-ujzuJ1ttQgjHQJEij4O/2+I8DZaUVZQCQgA4ysfqulI="
  [mod."github.com/pressly/goose/v3"]
    version = "v3.24.1"
    hash = "sha256-mf1KBaOB1H176TrZZq6h5LQIvUbFG/CLfBiddNL+JpE="
  [mod."github.com/redis/go-redis/extra/rediscmd/v9"]
    version = "v9.7.0"
    hash = "sha256-52BY3n/W63/9oAhGYPtSZzyxh/BY6Oo0lLKsxUzROEw="
  [mod."github.com/redis/go-redis/extra/redisotel/v9"]
    version = "v9.7.0"
    hash = "sha256-KaAC6Mhvl7SovecFPxmw1DTA7PEIK4UfVZ1PEL7z2tE="
  [mod."github.com/redis/go-redis/v9"]
    version = "v9.7.0"
    hash = "sha256-lpEMK1jBuwrIY7nrk5f9Ru4Y2FXDU4FxlVjXHjV5Ahc="
  [mod."github.com/remychantenay/slog-otel"]
    version = "v1.3.3"
    hash = "sha256-JyhEiUjFbAH0aB51JorhdZ1X+MubB9Eq+uwvSq2J8aI="
  [mod."github.com/sethvargo/go-envconfig"]
    version = "v1.1.0"
    hash = "sha256-WelRHfyZG9hrA4fbQcfBawb2ZXBQNT1ourEYHzQdZ4w="
  [mod."github.com/sethvargo/go-retry"]
    version = "v0.3.0"
    hash = "sha256-1ZnFRHAaQjralGKVRoCbiwCXXB3w4kS3f+2hK9S8lbU="
  [mod."github.com/shirou/gopsutil/v4"]
    version = "v4.25.1"
    hash = "sha256-hiM9ZcVagVO7WlWlCYbPQ1KlCz+uqIU6q2WUIpVBqbU="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.2"
    hash = "sha256-VKYxrrFb1nkX6Wu3tE5DoP9+fCttwSl9pgLN6567nck="
  [mod."github.com/stretchr/testify"]
    version = "v1.10.0"
    hash = "sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI="
  [mod."github.com/tklauser/go-sysconf"]
    version = "v0.3.14"
    hash = "sha256-DF4NKSQTv5Z0T89MGqao7GIABcYIazZXTIUHpKIud04="
  [mod."github.com/tklauser/numcpus"]
    version = "v0.9.0"
    hash = "sha256-YtdVe4wM/ggngdCewyCuWugkFpgXxtPvFlqBzNpJ+TI="
  [mod."github.com/veqryn/slog-context"]
    version = "v0.7.0"
    hash = "sha256-eCdqk/nS9o/Zsgi2q9425dRyrXCWKHNS8VG1hI352mU="
  [mod."github.com/vgarvardt/pgx-google-uuid/v5"]
    version = "v5.6.0"
    hash = "sha256-F+E8rFEHnmJKcCxl4hA3MosSEKqxytp5y7VMVZLFQEg="
  [mod."github.com/yuin/goldmark"]
    version = "v1.7.8"
    hash = "sha256-SNJMPPiXkRDLVOldrHN0ErC3bUB2VoWaLDkd9zmMATw="
  [mod."github.com/yusufpapurcu/wmi"]
    version = "v1.2.4"
    hash = "sha256-N+YDBjOW59YOsZ2lRBVtFsEEi48KhNQRb63/0ZSU3bA="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.1.0"
    hash = "sha256-cA9qCCu8P1NSJRxgmpfkfa5rKyn9X+Y/9FSmSd5xjyo="
  [mod."go.opentelemetry.io/contrib/instrumentation/host"]
    version = "v0.59.0"
    hash = "sha256-JPgReJq8OXSgoo+heOXSNGHmSpIGbyqybkacWqsaykE="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.59.0"
    hash = "sha256-zeC30S2MV7W2xxS5rVfPGhZO4jcdPpxxfy3QvBkt/pQ="
  [mod."go.opentelemetry.io/contrib/instrumentation/runtime"]
    version = "v0.59.0"
    hash = "sha256-Qqf3x+qaqw9n4f3H0RBRFwA+H0Z6dMbnLNCHeAJM2Q8="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.34.0"
    hash = "sha256-hnuuTSxaf9yMO/23xWdcTGNzvnnJiqUiL4nzYwUV5bc="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp"]
    version = "v1.34.0"
    hash = "sha256-xxQrrMs8m4kMbg+YA4bRUGZn1HFHrecI/1x9+mxBCU0="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.34.0"
    hash = "sha256-BC4a7j2ftvuwNkR2TeLekKBCHsP3MBFDZv831bo6XK4="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"]
    version = "v1.34.0"
    hash = "sha256-ZhnMo4PEV5gTnmPS/WJVaszR6NHD1aaezvn30QRuwb0="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.34.0"
    hash = "sha256-JklGKJiMf1fpsE9pmnuLUq26g6wVp173v4GWJ7Xp5s4="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.34.0"
    hash = "sha256-Af0INyxxGvtDRMt2szun/m56z6Rzwnxw/ckk7b/hR3M="
  [mod."go.opentelemetry.io/otel/sdk/metric"]
    version = "v1.34.0"
    hash = "sha256-jToGqaCoNGfypXaCgjl527zXyOrpACvhERcCqD8ogK4="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.34.0"
    hash = "sha256-u11KJ4WTDtcb0tVv7d/HOdhq8Ea+c1QPBO8MbsCQu9Q="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.5.0"
    hash = "sha256-k4jHapACIcAxN1q11TLorvjj6Sdn5P+InEC4sDtoZPY="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."golang.org/x/crypto"]
    version = "v0.33.0"
    hash = "sha256-U+a1nWirvCWHR5FDzXZZSCa/lUCHkmJoStbdjd8DnVY="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20250210185358-939b2ce775ac"
    hash = "sha256-3nIn0Ce1PFzVmVquJPN1vNwnyRtY3Zkx46affFb89Io="
  [mod."golang.org/x/net"]
    version = "v0.35.0"
    hash = "sha256-kCLhhvzHQCvUqC8kGhgMbVLUROG4ZeZNVGOVVv6tSAE="
  [mod."golang.org/x/sync"]
    version = "v0.11.0"
    hash = "sha256-5ZBfDJvNaUBM4Vhk0fgYblCGL3eBxiJL85nIE8LiKl0="
  [mod."golang.org/x/sys"]
    version = "v0.30.0"
    hash = "sha256-BuhWtwDkciVioc03rxty6G2vcZVnPX85lI7tgQOFVP8="
  [mod."golang.org/x/text"]
    version = "v0.22.0"
    hash = "sha256-kUwLNFk9K/YuWmO5/u2IshrmhT2CCuk+mAShSlTTeZo="
  [mod."golang.org/x/time"]
    version = "v0.10.0"
    hash = "sha256-vnlAME3gDR6R4cbCmSYAlR1Rjc0yUpkufTOPNvCdf6Q="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20250207221924-e9438ea467c6"
    hash = "sha256-T8mEp7ZkX7PXc64LN6rpfJMlFntonDyrYoaAnBjPkJA="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20250207221924-e9438ea467c6"
    hash = "sha256-qtyowIn84hBTrwH3R0m80udJ7OOo6wgAZbkRHcmNzrY="
  [mod."google.golang.org/grpc"]
    version = "v1.70.0"
    hash = "sha256-7SCJx6Y35O/0P3cFtELDXrOSOb+HshxaTQYdzv2gVmg="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.5"
    hash = "sha256-isupBiQUrKPEFzK94k5cgzM3Ab5fMXp352/zcsXV1JU="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."modernc.org/gc/v3"]
    version = "v3.0.0-20241004144649-1aea3fae8852"
    hash = "sha256-nwh2xVgoeq97cSzcOQShyraromxAkYa0vCym8LqRQG4="
