version: "3"

tasks:
  dev:
    desc: Start the app in dev mode with live-reloading.
    env:
      BANTERBUS_LOG_LEVEL: debug
    cmds:
      - air

  build:dev:
    desc: Build the app for development, generates all the files needed for the binary.
    deps:
      - generate
    cmds:
      - go build -o ./tmp/main .

  lint:
    desc: Runs the linter.
    cmds:
      - golangci-lint run {{.CLI_ARGS}} ./...

  docker:publish:
    desc: Build and publish the Docker image
    deps:
      - docker:build
    env:
      LOCAL_IMAGE: banterbus
      USER: $CI_REGISTRY_USER
      PASS: $CI_REGISTRY_PASSWORD
      REGISTRY: $CI_REGISTRY
      IMAGE_NAME: $CI_REGISTY_IMAGE
      IMAGE_TAG: $CI_COMMIT_TAG
    cmds:
      - nix build .#container
      - docker load < result
      - docker login -u $USER -p $PASS $REGISTRY
      - docker image tag $LOCAL_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      - docker push $IMAGE_NAME:$IMAGE_TAG

  format:
    desc: Runs the formatter.
    cmds:
      - goimports -local gitlab.com/hmajid2301/banterbus -w .
      - golines -m 120 -w .

  tests:
    desc: Runs all the tests.
    cmds:
      - gotestsum

  tests:unit:
    desc: Runs all the unit tests.
    cmds:
      - gotestsum --format testname --hide-summary=skipped -- {{.CLI_ARGS}} -skip '^TestIntegration' ./internal/...

  tests:integration:
    desc: Runs all the integration tests.
    cmds:
      - gotestsum --format testname --hide-summary=skipped -- {{.CLI_ARGS}} -run ^TestIntegration ./internal/...

  tests:e2e:
    desc: Runs e2e tests with playwright.
    cmds:
      - gotestsum --format standard-verbose -- {{.CLI_ARGS}} ./tests/e2e/...

  coverage:
    desc: show coverage
    cmds:
      - go tool cover -func coverage.txt
      - gocover-cobertura < coverage.txt > coverage.xml
    preconditions:
      - test -f coverage.txt

  generate:
    desc: Generates all the code needed for the project i.e. sqlc, templ & tailwindcss
    cmds:
      - templ generate
      - tailwindcss -i ./static/css/tailwind.css -o ./static/css/styles.css
      - sqlc generate

  release:
    desc: Release the CLI tool.
    cmds:
      - goreleaser release --clean --verbose
