// Code generated by mockery v2.52.1. DO NOT EDIT.

package websockets

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	db "gitlab.com/hmajid2301/banterbus/internal/store/db"

	service "gitlab.com/hmajid2301/banterbus/internal/service"

	time "time"

	uuid "github.com/google/uuid"
)

// MockRoundServicer is an autogenerated mock type for the RoundServicer type
type MockRoundServicer struct {
	mock.Mock
}

type MockRoundServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoundServicer) EXPECT() *MockRoundServicer_Expecter {
	return &MockRoundServicer_Expecter{mock: &_m.Mock}
}

// FinishGame provides a mock function with given fields: ctx, gameStateID
func (_m *MockRoundServicer) FinishGame(ctx context.Context, gameStateID uuid.UUID) error {
	ret := _m.Called(ctx, gameStateID)

	if len(ret) == 0 {
		panic("no return value specified for FinishGame")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, gameStateID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoundServicer_FinishGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishGame'
type MockRoundServicer_FinishGame_Call struct {
	*mock.Call
}

// FinishGame is a helper method to define mock.On call
//   - ctx context.Context
//   - gameStateID uuid.UUID
func (_e *MockRoundServicer_Expecter) FinishGame(ctx interface{}, gameStateID interface{}) *MockRoundServicer_FinishGame_Call {
	return &MockRoundServicer_FinishGame_Call{Call: _e.mock.On("FinishGame", ctx, gameStateID)}
}

func (_c *MockRoundServicer_FinishGame_Call) Run(run func(ctx context.Context, gameStateID uuid.UUID)) *MockRoundServicer_FinishGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoundServicer_FinishGame_Call) Return(_a0 error) *MockRoundServicer_FinishGame_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoundServicer_FinishGame_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRoundServicer_FinishGame_Call {
	_c.Call.Return(run)
	return _c
}

// GetGameState provides a mock function with given fields: ctx, playerID
func (_m *MockRoundServicer) GetGameState(ctx context.Context, playerID uuid.UUID) (db.FibbingItGameState, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetGameState")
	}

	var r0 db.FibbingItGameState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.FibbingItGameState, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.FibbingItGameState); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(db.FibbingItGameState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_GetGameState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGameState'
type MockRoundServicer_GetGameState_Call struct {
	*mock.Call
}

// GetGameState is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockRoundServicer_Expecter) GetGameState(ctx interface{}, playerID interface{}) *MockRoundServicer_GetGameState_Call {
	return &MockRoundServicer_GetGameState_Call{Call: _e.mock.On("GetGameState", ctx, playerID)}
}

func (_c *MockRoundServicer_GetGameState_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockRoundServicer_GetGameState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoundServicer_GetGameState_Call) Return(_a0 db.FibbingItGameState, _a1 error) *MockRoundServicer_GetGameState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_GetGameState_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.FibbingItGameState, error)) *MockRoundServicer_GetGameState_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuestionState provides a mock function with given fields: ctx, playerID
func (_m *MockRoundServicer) GetQuestionState(ctx context.Context, playerID uuid.UUID) (service.QuestionState, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionState")
	}

	var r0 service.QuestionState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (service.QuestionState, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) service.QuestionState); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(service.QuestionState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_GetQuestionState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestionState'
type MockRoundServicer_GetQuestionState_Call struct {
	*mock.Call
}

// GetQuestionState is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockRoundServicer_Expecter) GetQuestionState(ctx interface{}, playerID interface{}) *MockRoundServicer_GetQuestionState_Call {
	return &MockRoundServicer_GetQuestionState_Call{Call: _e.mock.On("GetQuestionState", ctx, playerID)}
}

func (_c *MockRoundServicer_GetQuestionState_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockRoundServicer_GetQuestionState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoundServicer_GetQuestionState_Call) Return(_a0 service.QuestionState, _a1 error) *MockRoundServicer_GetQuestionState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_GetQuestionState_Call) RunAndReturn(run func(context.Context, uuid.UUID) (service.QuestionState, error)) *MockRoundServicer_GetQuestionState_Call {
	_c.Call.Return(run)
	return _c
}

// GetRevealState provides a mock function with given fields: ctx, playerID
func (_m *MockRoundServicer) GetRevealState(ctx context.Context, playerID uuid.UUID) (service.RevealRoleState, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetRevealState")
	}

	var r0 service.RevealRoleState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (service.RevealRoleState, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) service.RevealRoleState); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(service.RevealRoleState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_GetRevealState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRevealState'
type MockRoundServicer_GetRevealState_Call struct {
	*mock.Call
}

// GetRevealState is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockRoundServicer_Expecter) GetRevealState(ctx interface{}, playerID interface{}) *MockRoundServicer_GetRevealState_Call {
	return &MockRoundServicer_GetRevealState_Call{Call: _e.mock.On("GetRevealState", ctx, playerID)}
}

func (_c *MockRoundServicer_GetRevealState_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockRoundServicer_GetRevealState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoundServicer_GetRevealState_Call) Return(_a0 service.RevealRoleState, _a1 error) *MockRoundServicer_GetRevealState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_GetRevealState_Call) RunAndReturn(run func(context.Context, uuid.UUID) (service.RevealRoleState, error)) *MockRoundServicer_GetRevealState_Call {
	_c.Call.Return(run)
	return _c
}

// GetScoreState provides a mock function with given fields: ctx, scoring, playerID
func (_m *MockRoundServicer) GetScoreState(ctx context.Context, scoring service.Scoring, playerID uuid.UUID) (service.ScoreState, error) {
	ret := _m.Called(ctx, scoring, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetScoreState")
	}

	var r0 service.ScoreState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.Scoring, uuid.UUID) (service.ScoreState, error)); ok {
		return rf(ctx, scoring, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.Scoring, uuid.UUID) service.ScoreState); ok {
		r0 = rf(ctx, scoring, playerID)
	} else {
		r0 = ret.Get(0).(service.ScoreState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.Scoring, uuid.UUID) error); ok {
		r1 = rf(ctx, scoring, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_GetScoreState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScoreState'
type MockRoundServicer_GetScoreState_Call struct {
	*mock.Call
}

// GetScoreState is a helper method to define mock.On call
//   - ctx context.Context
//   - scoring service.Scoring
//   - playerID uuid.UUID
func (_e *MockRoundServicer_Expecter) GetScoreState(ctx interface{}, scoring interface{}, playerID interface{}) *MockRoundServicer_GetScoreState_Call {
	return &MockRoundServicer_GetScoreState_Call{Call: _e.mock.On("GetScoreState", ctx, scoring, playerID)}
}

func (_c *MockRoundServicer_GetScoreState_Call) Run(run func(ctx context.Context, scoring service.Scoring, playerID uuid.UUID)) *MockRoundServicer_GetScoreState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.Scoring), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoundServicer_GetScoreState_Call) Return(_a0 service.ScoreState, _a1 error) *MockRoundServicer_GetScoreState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_GetScoreState_Call) RunAndReturn(run func(context.Context, service.Scoring, uuid.UUID) (service.ScoreState, error)) *MockRoundServicer_GetScoreState_Call {
	_c.Call.Return(run)
	return _c
}

// GetVotingState provides a mock function with given fields: ctx, playerID
func (_m *MockRoundServicer) GetVotingState(ctx context.Context, playerID uuid.UUID) (service.VotingState, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetVotingState")
	}

	var r0 service.VotingState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (service.VotingState, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) service.VotingState); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(service.VotingState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_GetVotingState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVotingState'
type MockRoundServicer_GetVotingState_Call struct {
	*mock.Call
}

// GetVotingState is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockRoundServicer_Expecter) GetVotingState(ctx interface{}, playerID interface{}) *MockRoundServicer_GetVotingState_Call {
	return &MockRoundServicer_GetVotingState_Call{Call: _e.mock.On("GetVotingState", ctx, playerID)}
}

func (_c *MockRoundServicer_GetVotingState_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockRoundServicer_GetVotingState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoundServicer_GetVotingState_Call) Return(_a0 service.VotingState, _a1 error) *MockRoundServicer_GetVotingState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_GetVotingState_Call) RunAndReturn(run func(context.Context, uuid.UUID) (service.VotingState, error)) *MockRoundServicer_GetVotingState_Call {
	_c.Call.Return(run)
	return _c
}

// GetWinnerState provides a mock function with given fields: ctx, playerID
func (_m *MockRoundServicer) GetWinnerState(ctx context.Context, playerID uuid.UUID) (service.WinnerState, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetWinnerState")
	}

	var r0 service.WinnerState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (service.WinnerState, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) service.WinnerState); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(service.WinnerState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_GetWinnerState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWinnerState'
type MockRoundServicer_GetWinnerState_Call struct {
	*mock.Call
}

// GetWinnerState is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockRoundServicer_Expecter) GetWinnerState(ctx interface{}, playerID interface{}) *MockRoundServicer_GetWinnerState_Call {
	return &MockRoundServicer_GetWinnerState_Call{Call: _e.mock.On("GetWinnerState", ctx, playerID)}
}

func (_c *MockRoundServicer_GetWinnerState_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockRoundServicer_GetWinnerState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoundServicer_GetWinnerState_Call) Return(_a0 service.WinnerState, _a1 error) *MockRoundServicer_GetWinnerState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_GetWinnerState_Call) RunAndReturn(run func(context.Context, uuid.UUID) (service.WinnerState, error)) *MockRoundServicer_GetWinnerState_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitAnswer provides a mock function with given fields: ctx, playerID, answer, submittedAt
func (_m *MockRoundServicer) SubmitAnswer(ctx context.Context, playerID uuid.UUID, answer string, submittedAt time.Time) error {
	ret := _m.Called(ctx, playerID, answer, submittedAt)

	if len(ret) == 0 {
		panic("no return value specified for SubmitAnswer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) error); ok {
		r0 = rf(ctx, playerID, answer, submittedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoundServicer_SubmitAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitAnswer'
type MockRoundServicer_SubmitAnswer_Call struct {
	*mock.Call
}

// SubmitAnswer is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
//   - answer string
//   - submittedAt time.Time
func (_e *MockRoundServicer_Expecter) SubmitAnswer(ctx interface{}, playerID interface{}, answer interface{}, submittedAt interface{}) *MockRoundServicer_SubmitAnswer_Call {
	return &MockRoundServicer_SubmitAnswer_Call{Call: _e.mock.On("SubmitAnswer", ctx, playerID, answer, submittedAt)}
}

func (_c *MockRoundServicer_SubmitAnswer_Call) Run(run func(ctx context.Context, playerID uuid.UUID, answer string, submittedAt time.Time)) *MockRoundServicer_SubmitAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRoundServicer_SubmitAnswer_Call) Return(_a0 error) *MockRoundServicer_SubmitAnswer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoundServicer_SubmitAnswer_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, time.Time) error) *MockRoundServicer_SubmitAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitVote provides a mock function with given fields: ctx, playerID, votedNickname, submittedAt
func (_m *MockRoundServicer) SubmitVote(ctx context.Context, playerID uuid.UUID, votedNickname string, submittedAt time.Time) (service.VotingState, error) {
	ret := _m.Called(ctx, playerID, votedNickname, submittedAt)

	if len(ret) == 0 {
		panic("no return value specified for SubmitVote")
	}

	var r0 service.VotingState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) (service.VotingState, error)); ok {
		return rf(ctx, playerID, votedNickname, submittedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) service.VotingState); ok {
		r0 = rf(ctx, playerID, votedNickname, submittedAt)
	} else {
		r0 = ret.Get(0).(service.VotingState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, time.Time) error); ok {
		r1 = rf(ctx, playerID, votedNickname, submittedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_SubmitVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitVote'
type MockRoundServicer_SubmitVote_Call struct {
	*mock.Call
}

// SubmitVote is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
//   - votedNickname string
//   - submittedAt time.Time
func (_e *MockRoundServicer_Expecter) SubmitVote(ctx interface{}, playerID interface{}, votedNickname interface{}, submittedAt interface{}) *MockRoundServicer_SubmitVote_Call {
	return &MockRoundServicer_SubmitVote_Call{Call: _e.mock.On("SubmitVote", ctx, playerID, votedNickname, submittedAt)}
}

func (_c *MockRoundServicer_SubmitVote_Call) Run(run func(ctx context.Context, playerID uuid.UUID, votedNickname string, submittedAt time.Time)) *MockRoundServicer_SubmitVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRoundServicer_SubmitVote_Call) Return(_a0 service.VotingState, _a1 error) *MockRoundServicer_SubmitVote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_SubmitVote_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, time.Time) (service.VotingState, error)) *MockRoundServicer_SubmitVote_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleAnswerIsReady provides a mock function with given fields: ctx, playerID, submittedAt
func (_m *MockRoundServicer) ToggleAnswerIsReady(ctx context.Context, playerID uuid.UUID, submittedAt time.Time) (bool, error) {
	ret := _m.Called(ctx, playerID, submittedAt)

	if len(ret) == 0 {
		panic("no return value specified for ToggleAnswerIsReady")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (bool, error)); ok {
		return rf(ctx, playerID, submittedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) bool); ok {
		r0 = rf(ctx, playerID, submittedAt)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, playerID, submittedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_ToggleAnswerIsReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleAnswerIsReady'
type MockRoundServicer_ToggleAnswerIsReady_Call struct {
	*mock.Call
}

// ToggleAnswerIsReady is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
//   - submittedAt time.Time
func (_e *MockRoundServicer_Expecter) ToggleAnswerIsReady(ctx interface{}, playerID interface{}, submittedAt interface{}) *MockRoundServicer_ToggleAnswerIsReady_Call {
	return &MockRoundServicer_ToggleAnswerIsReady_Call{Call: _e.mock.On("ToggleAnswerIsReady", ctx, playerID, submittedAt)}
}

func (_c *MockRoundServicer_ToggleAnswerIsReady_Call) Run(run func(ctx context.Context, playerID uuid.UUID, submittedAt time.Time)) *MockRoundServicer_ToggleAnswerIsReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRoundServicer_ToggleAnswerIsReady_Call) Return(_a0 bool, _a1 error) *MockRoundServicer_ToggleAnswerIsReady_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_ToggleAnswerIsReady_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (bool, error)) *MockRoundServicer_ToggleAnswerIsReady_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleVotingIsReady provides a mock function with given fields: ctx, playerID, submittedAt
func (_m *MockRoundServicer) ToggleVotingIsReady(ctx context.Context, playerID uuid.UUID, submittedAt time.Time) (bool, error) {
	ret := _m.Called(ctx, playerID, submittedAt)

	if len(ret) == 0 {
		panic("no return value specified for ToggleVotingIsReady")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (bool, error)); ok {
		return rf(ctx, playerID, submittedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) bool); ok {
		r0 = rf(ctx, playerID, submittedAt)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, playerID, submittedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_ToggleVotingIsReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleVotingIsReady'
type MockRoundServicer_ToggleVotingIsReady_Call struct {
	*mock.Call
}

// ToggleVotingIsReady is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
//   - submittedAt time.Time
func (_e *MockRoundServicer_Expecter) ToggleVotingIsReady(ctx interface{}, playerID interface{}, submittedAt interface{}) *MockRoundServicer_ToggleVotingIsReady_Call {
	return &MockRoundServicer_ToggleVotingIsReady_Call{Call: _e.mock.On("ToggleVotingIsReady", ctx, playerID, submittedAt)}
}

func (_c *MockRoundServicer_ToggleVotingIsReady_Call) Run(run func(ctx context.Context, playerID uuid.UUID, submittedAt time.Time)) *MockRoundServicer_ToggleVotingIsReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRoundServicer_ToggleVotingIsReady_Call) Return(_a0 bool, _a1 error) *MockRoundServicer_ToggleVotingIsReady_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_ToggleVotingIsReady_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (bool, error)) *MockRoundServicer_ToggleVotingIsReady_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStateToQuestion provides a mock function with given fields: ctx, gameStateID, deadline, nextRound
func (_m *MockRoundServicer) UpdateStateToQuestion(ctx context.Context, gameStateID uuid.UUID, deadline time.Time, nextRound bool) (service.QuestionState, error) {
	ret := _m.Called(ctx, gameStateID, deadline, nextRound)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStateToQuestion")
	}

	var r0 service.QuestionState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, bool) (service.QuestionState, error)); ok {
		return rf(ctx, gameStateID, deadline, nextRound)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, bool) service.QuestionState); ok {
		r0 = rf(ctx, gameStateID, deadline, nextRound)
	} else {
		r0 = ret.Get(0).(service.QuestionState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, bool) error); ok {
		r1 = rf(ctx, gameStateID, deadline, nextRound)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_UpdateStateToQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStateToQuestion'
type MockRoundServicer_UpdateStateToQuestion_Call struct {
	*mock.Call
}

// UpdateStateToQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - gameStateID uuid.UUID
//   - deadline time.Time
//   - nextRound bool
func (_e *MockRoundServicer_Expecter) UpdateStateToQuestion(ctx interface{}, gameStateID interface{}, deadline interface{}, nextRound interface{}) *MockRoundServicer_UpdateStateToQuestion_Call {
	return &MockRoundServicer_UpdateStateToQuestion_Call{Call: _e.mock.On("UpdateStateToQuestion", ctx, gameStateID, deadline, nextRound)}
}

func (_c *MockRoundServicer_UpdateStateToQuestion_Call) Run(run func(ctx context.Context, gameStateID uuid.UUID, deadline time.Time, nextRound bool)) *MockRoundServicer_UpdateStateToQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(bool))
	})
	return _c
}

func (_c *MockRoundServicer_UpdateStateToQuestion_Call) Return(_a0 service.QuestionState, _a1 error) *MockRoundServicer_UpdateStateToQuestion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_UpdateStateToQuestion_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, bool) (service.QuestionState, error)) *MockRoundServicer_UpdateStateToQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStateToReveal provides a mock function with given fields: ctx, gameStateID, deadline
func (_m *MockRoundServicer) UpdateStateToReveal(ctx context.Context, gameStateID uuid.UUID, deadline time.Time) (service.RevealRoleState, error) {
	ret := _m.Called(ctx, gameStateID, deadline)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStateToReveal")
	}

	var r0 service.RevealRoleState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (service.RevealRoleState, error)); ok {
		return rf(ctx, gameStateID, deadline)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) service.RevealRoleState); ok {
		r0 = rf(ctx, gameStateID, deadline)
	} else {
		r0 = ret.Get(0).(service.RevealRoleState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, gameStateID, deadline)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_UpdateStateToReveal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStateToReveal'
type MockRoundServicer_UpdateStateToReveal_Call struct {
	*mock.Call
}

// UpdateStateToReveal is a helper method to define mock.On call
//   - ctx context.Context
//   - gameStateID uuid.UUID
//   - deadline time.Time
func (_e *MockRoundServicer_Expecter) UpdateStateToReveal(ctx interface{}, gameStateID interface{}, deadline interface{}) *MockRoundServicer_UpdateStateToReveal_Call {
	return &MockRoundServicer_UpdateStateToReveal_Call{Call: _e.mock.On("UpdateStateToReveal", ctx, gameStateID, deadline)}
}

func (_c *MockRoundServicer_UpdateStateToReveal_Call) Run(run func(ctx context.Context, gameStateID uuid.UUID, deadline time.Time)) *MockRoundServicer_UpdateStateToReveal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRoundServicer_UpdateStateToReveal_Call) Return(_a0 service.RevealRoleState, _a1 error) *MockRoundServicer_UpdateStateToReveal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_UpdateStateToReveal_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (service.RevealRoleState, error)) *MockRoundServicer_UpdateStateToReveal_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStateToScore provides a mock function with given fields: ctx, gameStateID, deadline, scoring
func (_m *MockRoundServicer) UpdateStateToScore(ctx context.Context, gameStateID uuid.UUID, deadline time.Time, scoring service.Scoring) (service.ScoreState, error) {
	ret := _m.Called(ctx, gameStateID, deadline, scoring)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStateToScore")
	}

	var r0 service.ScoreState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, service.Scoring) (service.ScoreState, error)); ok {
		return rf(ctx, gameStateID, deadline, scoring)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, service.Scoring) service.ScoreState); ok {
		r0 = rf(ctx, gameStateID, deadline, scoring)
	} else {
		r0 = ret.Get(0).(service.ScoreState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, service.Scoring) error); ok {
		r1 = rf(ctx, gameStateID, deadline, scoring)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_UpdateStateToScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStateToScore'
type MockRoundServicer_UpdateStateToScore_Call struct {
	*mock.Call
}

// UpdateStateToScore is a helper method to define mock.On call
//   - ctx context.Context
//   - gameStateID uuid.UUID
//   - deadline time.Time
//   - scoring service.Scoring
func (_e *MockRoundServicer_Expecter) UpdateStateToScore(ctx interface{}, gameStateID interface{}, deadline interface{}, scoring interface{}) *MockRoundServicer_UpdateStateToScore_Call {
	return &MockRoundServicer_UpdateStateToScore_Call{Call: _e.mock.On("UpdateStateToScore", ctx, gameStateID, deadline, scoring)}
}

func (_c *MockRoundServicer_UpdateStateToScore_Call) Run(run func(ctx context.Context, gameStateID uuid.UUID, deadline time.Time, scoring service.Scoring)) *MockRoundServicer_UpdateStateToScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(service.Scoring))
	})
	return _c
}

func (_c *MockRoundServicer_UpdateStateToScore_Call) Return(_a0 service.ScoreState, _a1 error) *MockRoundServicer_UpdateStateToScore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_UpdateStateToScore_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, service.Scoring) (service.ScoreState, error)) *MockRoundServicer_UpdateStateToScore_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStateToVoting provides a mock function with given fields: ctx, gameStateID, deadline
func (_m *MockRoundServicer) UpdateStateToVoting(ctx context.Context, gameStateID uuid.UUID, deadline time.Time) (service.VotingState, error) {
	ret := _m.Called(ctx, gameStateID, deadline)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStateToVoting")
	}

	var r0 service.VotingState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (service.VotingState, error)); ok {
		return rf(ctx, gameStateID, deadline)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) service.VotingState); ok {
		r0 = rf(ctx, gameStateID, deadline)
	} else {
		r0 = ret.Get(0).(service.VotingState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, gameStateID, deadline)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_UpdateStateToVoting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStateToVoting'
type MockRoundServicer_UpdateStateToVoting_Call struct {
	*mock.Call
}

// UpdateStateToVoting is a helper method to define mock.On call
//   - ctx context.Context
//   - gameStateID uuid.UUID
//   - deadline time.Time
func (_e *MockRoundServicer_Expecter) UpdateStateToVoting(ctx interface{}, gameStateID interface{}, deadline interface{}) *MockRoundServicer_UpdateStateToVoting_Call {
	return &MockRoundServicer_UpdateStateToVoting_Call{Call: _e.mock.On("UpdateStateToVoting", ctx, gameStateID, deadline)}
}

func (_c *MockRoundServicer_UpdateStateToVoting_Call) Run(run func(ctx context.Context, gameStateID uuid.UUID, deadline time.Time)) *MockRoundServicer_UpdateStateToVoting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRoundServicer_UpdateStateToVoting_Call) Return(_a0 service.VotingState, _a1 error) *MockRoundServicer_UpdateStateToVoting_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_UpdateStateToVoting_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (service.VotingState, error)) *MockRoundServicer_UpdateStateToVoting_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStateToWinner provides a mock function with given fields: ctx, gameStateID, deadline
func (_m *MockRoundServicer) UpdateStateToWinner(ctx context.Context, gameStateID uuid.UUID, deadline time.Time) (service.WinnerState, error) {
	ret := _m.Called(ctx, gameStateID, deadline)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStateToWinner")
	}

	var r0 service.WinnerState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (service.WinnerState, error)); ok {
		return rf(ctx, gameStateID, deadline)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) service.WinnerState); ok {
		r0 = rf(ctx, gameStateID, deadline)
	} else {
		r0 = ret.Get(0).(service.WinnerState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, gameStateID, deadline)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundServicer_UpdateStateToWinner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStateToWinner'
type MockRoundServicer_UpdateStateToWinner_Call struct {
	*mock.Call
}

// UpdateStateToWinner is a helper method to define mock.On call
//   - ctx context.Context
//   - gameStateID uuid.UUID
//   - deadline time.Time
func (_e *MockRoundServicer_Expecter) UpdateStateToWinner(ctx interface{}, gameStateID interface{}, deadline interface{}) *MockRoundServicer_UpdateStateToWinner_Call {
	return &MockRoundServicer_UpdateStateToWinner_Call{Call: _e.mock.On("UpdateStateToWinner", ctx, gameStateID, deadline)}
}

func (_c *MockRoundServicer_UpdateStateToWinner_Call) Run(run func(ctx context.Context, gameStateID uuid.UUID, deadline time.Time)) *MockRoundServicer_UpdateStateToWinner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRoundServicer_UpdateStateToWinner_Call) Return(_a0 service.WinnerState, _a1 error) *MockRoundServicer_UpdateStateToWinner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundServicer_UpdateStateToWinner_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (service.WinnerState, error)) *MockRoundServicer_UpdateStateToWinner_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoundServicer creates a new instance of MockRoundServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoundServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoundServicer {
	mock := &MockRoundServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
