receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4317

processors:
  batch:
  
  # Transform the exported_job label to use environment/service format
  transform:
    metric_statements:
      - context: metric
        statements:
          # Extract environment and service name from resource attributes
          - set(attributes["exported_job"], Concat([resource.attributes["deployment.environment"], "/", resource.attributes["service.name"]], ""))

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"

extensions:
  health_check:
  pprof:
    endpoint: :1888

service:
  extensions: [health_check, pprof]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch, transform]
      exporters: [prometheus]
