// Code generated by mockery v2.46.0. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	db "gitlab.com/hmajid2301/banterbus/internal/store/db"

	uuid "github.com/google/uuid"
)

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// AddFibbingItAnswer provides a mock function with given fields: ctx, arg
func (_m *MockStorer) AddFibbingItAnswer(ctx context.Context, arg db.AddFibbingItAnswerParams) (db.FibbingItAnswer, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddFibbingItAnswer")
	}

	var r0 db.FibbingItAnswer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.AddFibbingItAnswerParams) (db.FibbingItAnswer, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.AddFibbingItAnswerParams) db.FibbingItAnswer); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.FibbingItAnswer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.AddFibbingItAnswerParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_AddFibbingItAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFibbingItAnswer'
type MockStorer_AddFibbingItAnswer_Call struct {
	*mock.Call
}

// AddFibbingItAnswer is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.AddFibbingItAnswerParams
func (_e *MockStorer_Expecter) AddFibbingItAnswer(ctx interface{}, arg interface{}) *MockStorer_AddFibbingItAnswer_Call {
	return &MockStorer_AddFibbingItAnswer_Call{Call: _e.mock.On("AddFibbingItAnswer", ctx, arg)}
}

func (_c *MockStorer_AddFibbingItAnswer_Call) Run(run func(ctx context.Context, arg db.AddFibbingItAnswerParams)) *MockStorer_AddFibbingItAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.AddFibbingItAnswerParams))
	})
	return _c
}

func (_c *MockStorer_AddFibbingItAnswer_Call) Return(_a0 db.FibbingItAnswer, _a1 error) *MockStorer_AddFibbingItAnswer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_AddFibbingItAnswer_Call) RunAndReturn(run func(context.Context, db.AddFibbingItAnswerParams) (db.FibbingItAnswer, error)) *MockStorer_AddFibbingItAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// AddFibbingItRole provides a mock function with given fields: ctx, arg
func (_m *MockStorer) AddFibbingItRole(ctx context.Context, arg db.AddFibbingItRoleParams) (db.FibbingItPlayerRole, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddFibbingItRole")
	}

	var r0 db.FibbingItPlayerRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.AddFibbingItRoleParams) (db.FibbingItPlayerRole, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.AddFibbingItRoleParams) db.FibbingItPlayerRole); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.FibbingItPlayerRole)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.AddFibbingItRoleParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_AddFibbingItRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFibbingItRole'
type MockStorer_AddFibbingItRole_Call struct {
	*mock.Call
}

// AddFibbingItRole is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.AddFibbingItRoleParams
func (_e *MockStorer_Expecter) AddFibbingItRole(ctx interface{}, arg interface{}) *MockStorer_AddFibbingItRole_Call {
	return &MockStorer_AddFibbingItRole_Call{Call: _e.mock.On("AddFibbingItRole", ctx, arg)}
}

func (_c *MockStorer_AddFibbingItRole_Call) Run(run func(ctx context.Context, arg db.AddFibbingItRoleParams)) *MockStorer_AddFibbingItRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.AddFibbingItRoleParams))
	})
	return _c
}

func (_c *MockStorer_AddFibbingItRole_Call) Return(_a0 db.FibbingItPlayerRole, _a1 error) *MockStorer_AddFibbingItRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_AddFibbingItRole_Call) RunAndReturn(run func(context.Context, db.AddFibbingItRoleParams) (db.FibbingItPlayerRole, error)) *MockStorer_AddFibbingItRole_Call {
	_c.Call.Return(run)
	return _c
}

// AddFibbingItRound provides a mock function with given fields: ctx, arg
func (_m *MockStorer) AddFibbingItRound(ctx context.Context, arg db.AddFibbingItRoundParams) (db.FibbingItRound, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddFibbingItRound")
	}

	var r0 db.FibbingItRound
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.AddFibbingItRoundParams) (db.FibbingItRound, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.AddFibbingItRoundParams) db.FibbingItRound); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.FibbingItRound)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.AddFibbingItRoundParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_AddFibbingItRound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFibbingItRound'
type MockStorer_AddFibbingItRound_Call struct {
	*mock.Call
}

// AddFibbingItRound is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.AddFibbingItRoundParams
func (_e *MockStorer_Expecter) AddFibbingItRound(ctx interface{}, arg interface{}) *MockStorer_AddFibbingItRound_Call {
	return &MockStorer_AddFibbingItRound_Call{Call: _e.mock.On("AddFibbingItRound", ctx, arg)}
}

func (_c *MockStorer_AddFibbingItRound_Call) Run(run func(ctx context.Context, arg db.AddFibbingItRoundParams)) *MockStorer_AddFibbingItRound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.AddFibbingItRoundParams))
	})
	return _c
}

func (_c *MockStorer_AddFibbingItRound_Call) Return(_a0 db.FibbingItRound, _a1 error) *MockStorer_AddFibbingItRound_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_AddFibbingItRound_Call) RunAndReturn(run func(context.Context, db.AddFibbingItRoundParams) (db.FibbingItRound, error)) *MockStorer_AddFibbingItRound_Call {
	_c.Call.Return(run)
	return _c
}

// AddGameState provides a mock function with given fields: ctx, arg
func (_m *MockStorer) AddGameState(ctx context.Context, arg db.AddGameStateParams) (db.GameState, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddGameState")
	}

	var r0 db.GameState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.AddGameStateParams) (db.GameState, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.AddGameStateParams) db.GameState); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.GameState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.AddGameStateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_AddGameState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGameState'
type MockStorer_AddGameState_Call struct {
	*mock.Call
}

// AddGameState is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.AddGameStateParams
func (_e *MockStorer_Expecter) AddGameState(ctx interface{}, arg interface{}) *MockStorer_AddGameState_Call {
	return &MockStorer_AddGameState_Call{Call: _e.mock.On("AddGameState", ctx, arg)}
}

func (_c *MockStorer_AddGameState_Call) Run(run func(ctx context.Context, arg db.AddGameStateParams)) *MockStorer_AddGameState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.AddGameStateParams))
	})
	return _c
}

func (_c *MockStorer_AddGameState_Call) Return(_a0 db.GameState, _a1 error) *MockStorer_AddGameState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_AddGameState_Call) RunAndReturn(run func(context.Context, db.AddGameStateParams) (db.GameState, error)) *MockStorer_AddGameState_Call {
	_c.Call.Return(run)
	return _c
}

// AddPlayer provides a mock function with given fields: ctx, arg
func (_m *MockStorer) AddPlayer(ctx context.Context, arg db.AddPlayerParams) (db.Player, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddPlayer")
	}

	var r0 db.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.AddPlayerParams) (db.Player, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.AddPlayerParams) db.Player); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Player)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.AddPlayerParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_AddPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlayer'
type MockStorer_AddPlayer_Call struct {
	*mock.Call
}

// AddPlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.AddPlayerParams
func (_e *MockStorer_Expecter) AddPlayer(ctx interface{}, arg interface{}) *MockStorer_AddPlayer_Call {
	return &MockStorer_AddPlayer_Call{Call: _e.mock.On("AddPlayer", ctx, arg)}
}

func (_c *MockStorer_AddPlayer_Call) Run(run func(ctx context.Context, arg db.AddPlayerParams)) *MockStorer_AddPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.AddPlayerParams))
	})
	return _c
}

func (_c *MockStorer_AddPlayer_Call) Return(_a0 db.Player, _a1 error) *MockStorer_AddPlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_AddPlayer_Call) RunAndReturn(run func(context.Context, db.AddPlayerParams) (db.Player, error)) *MockStorer_AddPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// AddPlayerToRoom provides a mock function with given fields: ctx, arg
func (_m *MockStorer) AddPlayerToRoom(ctx context.Context, arg db.AddPlayerToRoomArgs) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddPlayerToRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.AddPlayerToRoomArgs) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorer_AddPlayerToRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlayerToRoom'
type MockStorer_AddPlayerToRoom_Call struct {
	*mock.Call
}

// AddPlayerToRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.AddPlayerToRoomArgs
func (_e *MockStorer_Expecter) AddPlayerToRoom(ctx interface{}, arg interface{}) *MockStorer_AddPlayerToRoom_Call {
	return &MockStorer_AddPlayerToRoom_Call{Call: _e.mock.On("AddPlayerToRoom", ctx, arg)}
}

func (_c *MockStorer_AddPlayerToRoom_Call) Run(run func(ctx context.Context, arg db.AddPlayerToRoomArgs)) *MockStorer_AddPlayerToRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.AddPlayerToRoomArgs))
	})
	return _c
}

func (_c *MockStorer_AddPlayerToRoom_Call) Return(_a0 error) *MockStorer_AddPlayerToRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorer_AddPlayerToRoom_Call) RunAndReturn(run func(context.Context, db.AddPlayerToRoomArgs) error) *MockStorer_AddPlayerToRoom_Call {
	_c.Call.Return(run)
	return _c
}

// AddQuestion provides a mock function with given fields: ctx, arg
func (_m *MockStorer) AddQuestion(ctx context.Context, arg db.AddQuestionParams) (db.Question, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddQuestion")
	}

	var r0 db.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.AddQuestionParams) (db.Question, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.AddQuestionParams) db.Question); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Question)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.AddQuestionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_AddQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddQuestion'
type MockStorer_AddQuestion_Call struct {
	*mock.Call
}

// AddQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.AddQuestionParams
func (_e *MockStorer_Expecter) AddQuestion(ctx interface{}, arg interface{}) *MockStorer_AddQuestion_Call {
	return &MockStorer_AddQuestion_Call{Call: _e.mock.On("AddQuestion", ctx, arg)}
}

func (_c *MockStorer_AddQuestion_Call) Run(run func(ctx context.Context, arg db.AddQuestionParams)) *MockStorer_AddQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.AddQuestionParams))
	})
	return _c
}

func (_c *MockStorer_AddQuestion_Call) Return(_a0 db.Question, _a1 error) *MockStorer_AddQuestion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_AddQuestion_Call) RunAndReturn(run func(context.Context, db.AddQuestionParams) (db.Question, error)) *MockStorer_AddQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// AddQuestionsGroup provides a mock function with given fields: ctx, arg
func (_m *MockStorer) AddQuestionsGroup(ctx context.Context, arg db.AddQuestionsGroupParams) (db.QuestionsGroup, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddQuestionsGroup")
	}

	var r0 db.QuestionsGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.AddQuestionsGroupParams) (db.QuestionsGroup, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.AddQuestionsGroupParams) db.QuestionsGroup); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.QuestionsGroup)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.AddQuestionsGroupParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_AddQuestionsGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddQuestionsGroup'
type MockStorer_AddQuestionsGroup_Call struct {
	*mock.Call
}

// AddQuestionsGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.AddQuestionsGroupParams
func (_e *MockStorer_Expecter) AddQuestionsGroup(ctx interface{}, arg interface{}) *MockStorer_AddQuestionsGroup_Call {
	return &MockStorer_AddQuestionsGroup_Call{Call: _e.mock.On("AddQuestionsGroup", ctx, arg)}
}

func (_c *MockStorer_AddQuestionsGroup_Call) Run(run func(ctx context.Context, arg db.AddQuestionsGroupParams)) *MockStorer_AddQuestionsGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.AddQuestionsGroupParams))
	})
	return _c
}

func (_c *MockStorer_AddQuestionsGroup_Call) Return(_a0 db.QuestionsGroup, _a1 error) *MockStorer_AddQuestionsGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_AddQuestionsGroup_Call) RunAndReturn(run func(context.Context, db.AddQuestionsGroupParams) (db.QuestionsGroup, error)) *MockStorer_AddQuestionsGroup_Call {
	_c.Call.Return(run)
	return _c
}

// AddRoom provides a mock function with given fields: ctx, arg
func (_m *MockStorer) AddRoom(ctx context.Context, arg db.AddRoomParams) (db.Room, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddRoom")
	}

	var r0 db.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.AddRoomParams) (db.Room, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.AddRoomParams) db.Room); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.AddRoomParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_AddRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRoom'
type MockStorer_AddRoom_Call struct {
	*mock.Call
}

// AddRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.AddRoomParams
func (_e *MockStorer_Expecter) AddRoom(ctx interface{}, arg interface{}) *MockStorer_AddRoom_Call {
	return &MockStorer_AddRoom_Call{Call: _e.mock.On("AddRoom", ctx, arg)}
}

func (_c *MockStorer_AddRoom_Call) Run(run func(ctx context.Context, arg db.AddRoomParams)) *MockStorer_AddRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.AddRoomParams))
	})
	return _c
}

func (_c *MockStorer_AddRoom_Call) Return(_a0 db.Room, _a1 error) *MockStorer_AddRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_AddRoom_Call) RunAndReturn(run func(context.Context, db.AddRoomParams) (db.Room, error)) *MockStorer_AddRoom_Call {
	_c.Call.Return(run)
	return _c
}

// AddRoomPlayer provides a mock function with given fields: ctx, arg
func (_m *MockStorer) AddRoomPlayer(ctx context.Context, arg db.AddRoomPlayerParams) (db.RoomsPlayer, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddRoomPlayer")
	}

	var r0 db.RoomsPlayer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.AddRoomPlayerParams) (db.RoomsPlayer, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.AddRoomPlayerParams) db.RoomsPlayer); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.RoomsPlayer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.AddRoomPlayerParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_AddRoomPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRoomPlayer'
type MockStorer_AddRoomPlayer_Call struct {
	*mock.Call
}

// AddRoomPlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.AddRoomPlayerParams
func (_e *MockStorer_Expecter) AddRoomPlayer(ctx interface{}, arg interface{}) *MockStorer_AddRoomPlayer_Call {
	return &MockStorer_AddRoomPlayer_Call{Call: _e.mock.On("AddRoomPlayer", ctx, arg)}
}

func (_c *MockStorer_AddRoomPlayer_Call) Run(run func(ctx context.Context, arg db.AddRoomPlayerParams)) *MockStorer_AddRoomPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.AddRoomPlayerParams))
	})
	return _c
}

func (_c *MockStorer_AddRoomPlayer_Call) Return(_a0 db.RoomsPlayer, _a1 error) *MockStorer_AddRoomPlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_AddRoomPlayer_Call) RunAndReturn(run func(context.Context, db.AddRoomPlayerParams) (db.RoomsPlayer, error)) *MockStorer_AddRoomPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRoom provides a mock function with given fields: ctx, arg
func (_m *MockStorer) CreateRoom(ctx context.Context, arg db.CreateRoomParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRoomParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorer_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type MockStorer_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateRoomParams
func (_e *MockStorer_Expecter) CreateRoom(ctx interface{}, arg interface{}) *MockStorer_CreateRoom_Call {
	return &MockStorer_CreateRoom_Call{Call: _e.mock.On("CreateRoom", ctx, arg)}
}

func (_c *MockStorer_CreateRoom_Call) Run(run func(ctx context.Context, arg db.CreateRoomParams)) *MockStorer_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateRoomParams))
	})
	return _c
}

func (_c *MockStorer_CreateRoom_Call) Return(_a0 error) *MockStorer_CreateRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorer_CreateRoom_Call) RunAndReturn(run func(context.Context, db.CreateRoomParams) error) *MockStorer_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPlayerAnswerIsReady provides a mock function with given fields: ctx, playerID
func (_m *MockStorer) GetAllPlayerAnswerIsReady(ctx context.Context, playerID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPlayerAnswerIsReady")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetAllPlayerAnswerIsReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPlayerAnswerIsReady'
type MockStorer_GetAllPlayerAnswerIsReady_Call struct {
	*mock.Call
}

// GetAllPlayerAnswerIsReady is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockStorer_Expecter) GetAllPlayerAnswerIsReady(ctx interface{}, playerID interface{}) *MockStorer_GetAllPlayerAnswerIsReady_Call {
	return &MockStorer_GetAllPlayerAnswerIsReady_Call{Call: _e.mock.On("GetAllPlayerAnswerIsReady", ctx, playerID)}
}

func (_c *MockStorer_GetAllPlayerAnswerIsReady_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockStorer_GetAllPlayerAnswerIsReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_GetAllPlayerAnswerIsReady_Call) Return(_a0 bool, _a1 error) *MockStorer_GetAllPlayerAnswerIsReady_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetAllPlayerAnswerIsReady_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *MockStorer_GetAllPlayerAnswerIsReady_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPlayerByRoomCode provides a mock function with given fields: ctx, roomCode
func (_m *MockStorer) GetAllPlayerByRoomCode(ctx context.Context, roomCode string) ([]db.GetAllPlayerByRoomCodeRow, error) {
	ret := _m.Called(ctx, roomCode)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPlayerByRoomCode")
	}

	var r0 []db.GetAllPlayerByRoomCodeRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]db.GetAllPlayerByRoomCodeRow, error)); ok {
		return rf(ctx, roomCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []db.GetAllPlayerByRoomCodeRow); ok {
		r0 = rf(ctx, roomCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetAllPlayerByRoomCodeRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roomCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetAllPlayerByRoomCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPlayerByRoomCode'
type MockStorer_GetAllPlayerByRoomCode_Call struct {
	*mock.Call
}

// GetAllPlayerByRoomCode is a helper method to define mock.On call
//   - ctx context.Context
//   - roomCode string
func (_e *MockStorer_Expecter) GetAllPlayerByRoomCode(ctx interface{}, roomCode interface{}) *MockStorer_GetAllPlayerByRoomCode_Call {
	return &MockStorer_GetAllPlayerByRoomCode_Call{Call: _e.mock.On("GetAllPlayerByRoomCode", ctx, roomCode)}
}

func (_c *MockStorer_GetAllPlayerByRoomCode_Call) Run(run func(ctx context.Context, roomCode string)) *MockStorer_GetAllPlayerByRoomCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorer_GetAllPlayerByRoomCode_Call) Return(_a0 []db.GetAllPlayerByRoomCodeRow, _a1 error) *MockStorer_GetAllPlayerByRoomCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetAllPlayerByRoomCode_Call) RunAndReturn(run func(context.Context, string) ([]db.GetAllPlayerByRoomCodeRow, error)) *MockStorer_GetAllPlayerByRoomCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPlayersInRoom provides a mock function with given fields: ctx, playerID
func (_m *MockStorer) GetAllPlayersInRoom(ctx context.Context, playerID uuid.UUID) ([]db.GetAllPlayersInRoomRow, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPlayersInRoom")
	}

	var r0 []db.GetAllPlayersInRoomRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]db.GetAllPlayersInRoomRow, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []db.GetAllPlayersInRoomRow); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetAllPlayersInRoomRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetAllPlayersInRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPlayersInRoom'
type MockStorer_GetAllPlayersInRoom_Call struct {
	*mock.Call
}

// GetAllPlayersInRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockStorer_Expecter) GetAllPlayersInRoom(ctx interface{}, playerID interface{}) *MockStorer_GetAllPlayersInRoom_Call {
	return &MockStorer_GetAllPlayersInRoom_Call{Call: _e.mock.On("GetAllPlayersInRoom", ctx, playerID)}
}

func (_c *MockStorer_GetAllPlayersInRoom_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockStorer_GetAllPlayersInRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_GetAllPlayersInRoom_Call) Return(_a0 []db.GetAllPlayersInRoomRow, _a1 error) *MockStorer_GetAllPlayersInRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetAllPlayersInRoom_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]db.GetAllPlayersInRoomRow, error)) *MockStorer_GetAllPlayersInRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentQuestionByPlayerID provides a mock function with given fields: ctx, id
func (_m *MockStorer) GetCurrentQuestionByPlayerID(ctx context.Context, id uuid.UUID) (db.GetCurrentQuestionByPlayerIDRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentQuestionByPlayerID")
	}

	var r0 db.GetCurrentQuestionByPlayerIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.GetCurrentQuestionByPlayerIDRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.GetCurrentQuestionByPlayerIDRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetCurrentQuestionByPlayerIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetCurrentQuestionByPlayerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentQuestionByPlayerID'
type MockStorer_GetCurrentQuestionByPlayerID_Call struct {
	*mock.Call
}

// GetCurrentQuestionByPlayerID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStorer_Expecter) GetCurrentQuestionByPlayerID(ctx interface{}, id interface{}) *MockStorer_GetCurrentQuestionByPlayerID_Call {
	return &MockStorer_GetCurrentQuestionByPlayerID_Call{Call: _e.mock.On("GetCurrentQuestionByPlayerID", ctx, id)}
}

func (_c *MockStorer_GetCurrentQuestionByPlayerID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStorer_GetCurrentQuestionByPlayerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_GetCurrentQuestionByPlayerID_Call) Return(_a0 db.GetCurrentQuestionByPlayerIDRow, _a1 error) *MockStorer_GetCurrentQuestionByPlayerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetCurrentQuestionByPlayerID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.GetCurrentQuestionByPlayerIDRow, error)) *MockStorer_GetCurrentQuestionByPlayerID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGameState provides a mock function with given fields: ctx, id
func (_m *MockStorer) GetGameState(ctx context.Context, id uuid.UUID) (db.GameState, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGameState")
	}

	var r0 db.GameState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.GameState, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.GameState); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GameState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetGameState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGameState'
type MockStorer_GetGameState_Call struct {
	*mock.Call
}

// GetGameState is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStorer_Expecter) GetGameState(ctx interface{}, id interface{}) *MockStorer_GetGameState_Call {
	return &MockStorer_GetGameState_Call{Call: _e.mock.On("GetGameState", ctx, id)}
}

func (_c *MockStorer_GetGameState_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStorer_GetGameState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_GetGameState_Call) Return(_a0 db.GameState, _a1 error) *MockStorer_GetGameState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetGameState_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.GameState, error)) *MockStorer_GetGameState_Call {
	_c.Call.Return(run)
	return _c
}

// GetGameStateByPlayerID provides a mock function with given fields: ctx, playerID
func (_m *MockStorer) GetGameStateByPlayerID(ctx context.Context, playerID uuid.UUID) (db.GameState, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetGameStateByPlayerID")
	}

	var r0 db.GameState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.GameState, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.GameState); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(db.GameState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetGameStateByPlayerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGameStateByPlayerID'
type MockStorer_GetGameStateByPlayerID_Call struct {
	*mock.Call
}

// GetGameStateByPlayerID is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockStorer_Expecter) GetGameStateByPlayerID(ctx interface{}, playerID interface{}) *MockStorer_GetGameStateByPlayerID_Call {
	return &MockStorer_GetGameStateByPlayerID_Call{Call: _e.mock.On("GetGameStateByPlayerID", ctx, playerID)}
}

func (_c *MockStorer_GetGameStateByPlayerID_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockStorer_GetGameStateByPlayerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_GetGameStateByPlayerID_Call) Return(_a0 db.GameState, _a1 error) *MockStorer_GetGameStateByPlayerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetGameStateByPlayerID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.GameState, error)) *MockStorer_GetGameStateByPlayerID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestRoundByGameStateID provides a mock function with given fields: ctx, id
func (_m *MockStorer) GetLatestRoundByGameStateID(ctx context.Context, id uuid.UUID) (db.GetLatestRoundByGameStateIDRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestRoundByGameStateID")
	}

	var r0 db.GetLatestRoundByGameStateIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.GetLatestRoundByGameStateIDRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.GetLatestRoundByGameStateIDRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetLatestRoundByGameStateIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetLatestRoundByGameStateID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestRoundByGameStateID'
type MockStorer_GetLatestRoundByGameStateID_Call struct {
	*mock.Call
}

// GetLatestRoundByGameStateID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStorer_Expecter) GetLatestRoundByGameStateID(ctx interface{}, id interface{}) *MockStorer_GetLatestRoundByGameStateID_Call {
	return &MockStorer_GetLatestRoundByGameStateID_Call{Call: _e.mock.On("GetLatestRoundByGameStateID", ctx, id)}
}

func (_c *MockStorer_GetLatestRoundByGameStateID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStorer_GetLatestRoundByGameStateID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_GetLatestRoundByGameStateID_Call) Return(_a0 db.GetLatestRoundByGameStateIDRow, _a1 error) *MockStorer_GetLatestRoundByGameStateID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetLatestRoundByGameStateID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.GetLatestRoundByGameStateIDRow, error)) *MockStorer_GetLatestRoundByGameStateID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestRoundByPlayerID provides a mock function with given fields: ctx, playerID
func (_m *MockStorer) GetLatestRoundByPlayerID(ctx context.Context, playerID uuid.UUID) (db.GetLatestRoundByPlayerIDRow, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestRoundByPlayerID")
	}

	var r0 db.GetLatestRoundByPlayerIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.GetLatestRoundByPlayerIDRow, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.GetLatestRoundByPlayerIDRow); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(db.GetLatestRoundByPlayerIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetLatestRoundByPlayerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestRoundByPlayerID'
type MockStorer_GetLatestRoundByPlayerID_Call struct {
	*mock.Call
}

// GetLatestRoundByPlayerID is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockStorer_Expecter) GetLatestRoundByPlayerID(ctx interface{}, playerID interface{}) *MockStorer_GetLatestRoundByPlayerID_Call {
	return &MockStorer_GetLatestRoundByPlayerID_Call{Call: _e.mock.On("GetLatestRoundByPlayerID", ctx, playerID)}
}

func (_c *MockStorer_GetLatestRoundByPlayerID_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockStorer_GetLatestRoundByPlayerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_GetLatestRoundByPlayerID_Call) Return(_a0 db.GetLatestRoundByPlayerIDRow, _a1 error) *MockStorer_GetLatestRoundByPlayerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetLatestRoundByPlayerID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.GetLatestRoundByPlayerIDRow, error)) *MockStorer_GetLatestRoundByPlayerID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayerByID provides a mock function with given fields: ctx, id
func (_m *MockStorer) GetPlayerByID(ctx context.Context, id uuid.UUID) (db.Player, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerByID")
	}

	var r0 db.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.Player, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.Player); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Player)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetPlayerByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayerByID'
type MockStorer_GetPlayerByID_Call struct {
	*mock.Call
}

// GetPlayerByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStorer_Expecter) GetPlayerByID(ctx interface{}, id interface{}) *MockStorer_GetPlayerByID_Call {
	return &MockStorer_GetPlayerByID_Call{Call: _e.mock.On("GetPlayerByID", ctx, id)}
}

func (_c *MockStorer_GetPlayerByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStorer_GetPlayerByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_GetPlayerByID_Call) Return(_a0 db.Player, _a1 error) *MockStorer_GetPlayerByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetPlayerByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.Player, error)) *MockStorer_GetPlayerByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRandomQuestionByRound provides a mock function with given fields: ctx, arg
func (_m *MockStorer) GetRandomQuestionByRound(ctx context.Context, arg db.GetRandomQuestionByRoundParams) (db.Question, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomQuestionByRound")
	}

	var r0 db.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetRandomQuestionByRoundParams) (db.Question, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetRandomQuestionByRoundParams) db.Question); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Question)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetRandomQuestionByRoundParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetRandomQuestionByRound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomQuestionByRound'
type MockStorer_GetRandomQuestionByRound_Call struct {
	*mock.Call
}

// GetRandomQuestionByRound is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetRandomQuestionByRoundParams
func (_e *MockStorer_Expecter) GetRandomQuestionByRound(ctx interface{}, arg interface{}) *MockStorer_GetRandomQuestionByRound_Call {
	return &MockStorer_GetRandomQuestionByRound_Call{Call: _e.mock.On("GetRandomQuestionByRound", ctx, arg)}
}

func (_c *MockStorer_GetRandomQuestionByRound_Call) Run(run func(ctx context.Context, arg db.GetRandomQuestionByRoundParams)) *MockStorer_GetRandomQuestionByRound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.GetRandomQuestionByRoundParams))
	})
	return _c
}

func (_c *MockStorer_GetRandomQuestionByRound_Call) Return(_a0 db.Question, _a1 error) *MockStorer_GetRandomQuestionByRound_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetRandomQuestionByRound_Call) RunAndReturn(run func(context.Context, db.GetRandomQuestionByRoundParams) (db.Question, error)) *MockStorer_GetRandomQuestionByRound_Call {
	_c.Call.Return(run)
	return _c
}

// GetRandomQuestionInGroup provides a mock function with given fields: ctx, arg
func (_m *MockStorer) GetRandomQuestionInGroup(ctx context.Context, arg db.GetRandomQuestionInGroupParams) (db.GetRandomQuestionInGroupRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomQuestionInGroup")
	}

	var r0 db.GetRandomQuestionInGroupRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetRandomQuestionInGroupParams) (db.GetRandomQuestionInGroupRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetRandomQuestionInGroupParams) db.GetRandomQuestionInGroupRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.GetRandomQuestionInGroupRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetRandomQuestionInGroupParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetRandomQuestionInGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomQuestionInGroup'
type MockStorer_GetRandomQuestionInGroup_Call struct {
	*mock.Call
}

// GetRandomQuestionInGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetRandomQuestionInGroupParams
func (_e *MockStorer_Expecter) GetRandomQuestionInGroup(ctx interface{}, arg interface{}) *MockStorer_GetRandomQuestionInGroup_Call {
	return &MockStorer_GetRandomQuestionInGroup_Call{Call: _e.mock.On("GetRandomQuestionInGroup", ctx, arg)}
}

func (_c *MockStorer_GetRandomQuestionInGroup_Call) Run(run func(ctx context.Context, arg db.GetRandomQuestionInGroupParams)) *MockStorer_GetRandomQuestionInGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.GetRandomQuestionInGroupParams))
	})
	return _c
}

func (_c *MockStorer_GetRandomQuestionInGroup_Call) Return(_a0 db.GetRandomQuestionInGroupRow, _a1 error) *MockStorer_GetRandomQuestionInGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetRandomQuestionInGroup_Call) RunAndReturn(run func(context.Context, db.GetRandomQuestionInGroupParams) (db.GetRandomQuestionInGroupRow, error)) *MockStorer_GetRandomQuestionInGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomByCode provides a mock function with given fields: ctx, roomCode
func (_m *MockStorer) GetRoomByCode(ctx context.Context, roomCode string) (db.Room, error) {
	ret := _m.Called(ctx, roomCode)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomByCode")
	}

	var r0 db.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.Room, error)); ok {
		return rf(ctx, roomCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.Room); ok {
		r0 = rf(ctx, roomCode)
	} else {
		r0 = ret.Get(0).(db.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roomCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetRoomByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomByCode'
type MockStorer_GetRoomByCode_Call struct {
	*mock.Call
}

// GetRoomByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - roomCode string
func (_e *MockStorer_Expecter) GetRoomByCode(ctx interface{}, roomCode interface{}) *MockStorer_GetRoomByCode_Call {
	return &MockStorer_GetRoomByCode_Call{Call: _e.mock.On("GetRoomByCode", ctx, roomCode)}
}

func (_c *MockStorer_GetRoomByCode_Call) Run(run func(ctx context.Context, roomCode string)) *MockStorer_GetRoomByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorer_GetRoomByCode_Call) Return(_a0 db.Room, _a1 error) *MockStorer_GetRoomByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetRoomByCode_Call) RunAndReturn(run func(context.Context, string) (db.Room, error)) *MockStorer_GetRoomByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomByPlayerID provides a mock function with given fields: ctx, playerID
func (_m *MockStorer) GetRoomByPlayerID(ctx context.Context, playerID uuid.UUID) (db.Room, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomByPlayerID")
	}

	var r0 db.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.Room, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.Room); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(db.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetRoomByPlayerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomByPlayerID'
type MockStorer_GetRoomByPlayerID_Call struct {
	*mock.Call
}

// GetRoomByPlayerID is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockStorer_Expecter) GetRoomByPlayerID(ctx interface{}, playerID interface{}) *MockStorer_GetRoomByPlayerID_Call {
	return &MockStorer_GetRoomByPlayerID_Call{Call: _e.mock.On("GetRoomByPlayerID", ctx, playerID)}
}

func (_c *MockStorer_GetRoomByPlayerID_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockStorer_GetRoomByPlayerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_GetRoomByPlayerID_Call) Return(_a0 db.Room, _a1 error) *MockStorer_GetRoomByPlayerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetRoomByPlayerID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.Room, error)) *MockStorer_GetRoomByPlayerID_Call {
	_c.Call.Return(run)
	return _c
}

// GetVotingState provides a mock function with given fields: ctx, id
func (_m *MockStorer) GetVotingState(ctx context.Context, id uuid.UUID) ([]db.GetVotingStateRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVotingState")
	}

	var r0 []db.GetVotingStateRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]db.GetVotingStateRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []db.GetVotingStateRow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetVotingStateRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_GetVotingState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVotingState'
type MockStorer_GetVotingState_Call struct {
	*mock.Call
}

// GetVotingState is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStorer_Expecter) GetVotingState(ctx interface{}, id interface{}) *MockStorer_GetVotingState_Call {
	return &MockStorer_GetVotingState_Call{Call: _e.mock.On("GetVotingState", ctx, id)}
}

func (_c *MockStorer_GetVotingState_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStorer_GetVotingState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_GetVotingState_Call) Return(_a0 []db.GetVotingStateRow, _a1 error) *MockStorer_GetVotingState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_GetVotingState_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]db.GetVotingStateRow, error)) *MockStorer_GetVotingState_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePlayerFromRoom provides a mock function with given fields: ctx, playerID
func (_m *MockStorer) RemovePlayerFromRoom(ctx context.Context, playerID uuid.UUID) (db.RoomsPlayer, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePlayerFromRoom")
	}

	var r0 db.RoomsPlayer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.RoomsPlayer, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.RoomsPlayer); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(db.RoomsPlayer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_RemovePlayerFromRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePlayerFromRoom'
type MockStorer_RemovePlayerFromRoom_Call struct {
	*mock.Call
}

// RemovePlayerFromRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockStorer_Expecter) RemovePlayerFromRoom(ctx interface{}, playerID interface{}) *MockStorer_RemovePlayerFromRoom_Call {
	return &MockStorer_RemovePlayerFromRoom_Call{Call: _e.mock.On("RemovePlayerFromRoom", ctx, playerID)}
}

func (_c *MockStorer_RemovePlayerFromRoom_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockStorer_RemovePlayerFromRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_RemovePlayerFromRoom_Call) Return(_a0 db.RoomsPlayer, _a1 error) *MockStorer_RemovePlayerFromRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_RemovePlayerFromRoom_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.RoomsPlayer, error)) *MockStorer_RemovePlayerFromRoom_Call {
	_c.Call.Return(run)
	return _c
}

// StartGame provides a mock function with given fields: ctx, arg
func (_m *MockStorer) StartGame(ctx context.Context, arg db.StartGameArgs) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for StartGame")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.StartGameArgs) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorer_StartGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartGame'
type MockStorer_StartGame_Call struct {
	*mock.Call
}

// StartGame is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.StartGameArgs
func (_e *MockStorer_Expecter) StartGame(ctx interface{}, arg interface{}) *MockStorer_StartGame_Call {
	return &MockStorer_StartGame_Call{Call: _e.mock.On("StartGame", ctx, arg)}
}

func (_c *MockStorer_StartGame_Call) Run(run func(ctx context.Context, arg db.StartGameArgs)) *MockStorer_StartGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.StartGameArgs))
	})
	return _c
}

func (_c *MockStorer_StartGame_Call) Return(_a0 error) *MockStorer_StartGame_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorer_StartGame_Call) RunAndReturn(run func(context.Context, db.StartGameArgs) error) *MockStorer_StartGame_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleAnswerIsReady provides a mock function with given fields: ctx, playerID
func (_m *MockStorer) ToggleAnswerIsReady(ctx context.Context, playerID uuid.UUID) (db.FibbingItAnswer, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for ToggleAnswerIsReady")
	}

	var r0 db.FibbingItAnswer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.FibbingItAnswer, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.FibbingItAnswer); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(db.FibbingItAnswer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_ToggleAnswerIsReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleAnswerIsReady'
type MockStorer_ToggleAnswerIsReady_Call struct {
	*mock.Call
}

// ToggleAnswerIsReady is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockStorer_Expecter) ToggleAnswerIsReady(ctx interface{}, playerID interface{}) *MockStorer_ToggleAnswerIsReady_Call {
	return &MockStorer_ToggleAnswerIsReady_Call{Call: _e.mock.On("ToggleAnswerIsReady", ctx, playerID)}
}

func (_c *MockStorer_ToggleAnswerIsReady_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockStorer_ToggleAnswerIsReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_ToggleAnswerIsReady_Call) Return(_a0 db.FibbingItAnswer, _a1 error) *MockStorer_ToggleAnswerIsReady_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_ToggleAnswerIsReady_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.FibbingItAnswer, error)) *MockStorer_ToggleAnswerIsReady_Call {
	_c.Call.Return(run)
	return _c
}

// TogglePlayerIsReady provides a mock function with given fields: ctx, id
func (_m *MockStorer) TogglePlayerIsReady(ctx context.Context, id uuid.UUID) (db.Player, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for TogglePlayerIsReady")
	}

	var r0 db.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.Player, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.Player); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Player)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_TogglePlayerIsReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TogglePlayerIsReady'
type MockStorer_TogglePlayerIsReady_Call struct {
	*mock.Call
}

// TogglePlayerIsReady is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStorer_Expecter) TogglePlayerIsReady(ctx interface{}, id interface{}) *MockStorer_TogglePlayerIsReady_Call {
	return &MockStorer_TogglePlayerIsReady_Call{Call: _e.mock.On("TogglePlayerIsReady", ctx, id)}
}

func (_c *MockStorer_TogglePlayerIsReady_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStorer_TogglePlayerIsReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorer_TogglePlayerIsReady_Call) Return(_a0 db.Player, _a1 error) *MockStorer_TogglePlayerIsReady_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_TogglePlayerIsReady_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.Player, error)) *MockStorer_TogglePlayerIsReady_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAvatar provides a mock function with given fields: ctx, arg
func (_m *MockStorer) UpdateAvatar(ctx context.Context, arg db.UpdateAvatarParams) (db.Player, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAvatar")
	}

	var r0 db.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateAvatarParams) (db.Player, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateAvatarParams) db.Player); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Player)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateAvatarParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_UpdateAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAvatar'
type MockStorer_UpdateAvatar_Call struct {
	*mock.Call
}

// UpdateAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateAvatarParams
func (_e *MockStorer_Expecter) UpdateAvatar(ctx interface{}, arg interface{}) *MockStorer_UpdateAvatar_Call {
	return &MockStorer_UpdateAvatar_Call{Call: _e.mock.On("UpdateAvatar", ctx, arg)}
}

func (_c *MockStorer_UpdateAvatar_Call) Run(run func(ctx context.Context, arg db.UpdateAvatarParams)) *MockStorer_UpdateAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateAvatarParams))
	})
	return _c
}

func (_c *MockStorer_UpdateAvatar_Call) Return(_a0 db.Player, _a1 error) *MockStorer_UpdateAvatar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_UpdateAvatar_Call) RunAndReturn(run func(context.Context, db.UpdateAvatarParams) (db.Player, error)) *MockStorer_UpdateAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGameState provides a mock function with given fields: ctx, arg
func (_m *MockStorer) UpdateGameState(ctx context.Context, arg db.UpdateGameStateParams) (db.GameState, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGameState")
	}

	var r0 db.GameState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateGameStateParams) (db.GameState, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateGameStateParams) db.GameState); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.GameState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateGameStateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_UpdateGameState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGameState'
type MockStorer_UpdateGameState_Call struct {
	*mock.Call
}

// UpdateGameState is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateGameStateParams
func (_e *MockStorer_Expecter) UpdateGameState(ctx interface{}, arg interface{}) *MockStorer_UpdateGameState_Call {
	return &MockStorer_UpdateGameState_Call{Call: _e.mock.On("UpdateGameState", ctx, arg)}
}

func (_c *MockStorer_UpdateGameState_Call) Run(run func(ctx context.Context, arg db.UpdateGameStateParams)) *MockStorer_UpdateGameState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateGameStateParams))
	})
	return _c
}

func (_c *MockStorer_UpdateGameState_Call) Return(_a0 db.GameState, _a1 error) *MockStorer_UpdateGameState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_UpdateGameState_Call) RunAndReturn(run func(context.Context, db.UpdateGameStateParams) (db.GameState, error)) *MockStorer_UpdateGameState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNickname provides a mock function with given fields: ctx, arg
func (_m *MockStorer) UpdateNickname(ctx context.Context, arg db.UpdateNicknameParams) (db.Player, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNickname")
	}

	var r0 db.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateNicknameParams) (db.Player, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateNicknameParams) db.Player); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Player)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateNicknameParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_UpdateNickname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNickname'
type MockStorer_UpdateNickname_Call struct {
	*mock.Call
}

// UpdateNickname is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateNicknameParams
func (_e *MockStorer_Expecter) UpdateNickname(ctx interface{}, arg interface{}) *MockStorer_UpdateNickname_Call {
	return &MockStorer_UpdateNickname_Call{Call: _e.mock.On("UpdateNickname", ctx, arg)}
}

func (_c *MockStorer_UpdateNickname_Call) Run(run func(ctx context.Context, arg db.UpdateNicknameParams)) *MockStorer_UpdateNickname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateNicknameParams))
	})
	return _c
}

func (_c *MockStorer_UpdateNickname_Call) Return(_a0 db.Player, _a1 error) *MockStorer_UpdateNickname_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_UpdateNickname_Call) RunAndReturn(run func(context.Context, db.UpdateNicknameParams) (db.Player, error)) *MockStorer_UpdateNickname_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRoomState provides a mock function with given fields: ctx, arg
func (_m *MockStorer) UpdateRoomState(ctx context.Context, arg db.UpdateRoomStateParams) (db.Room, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoomState")
	}

	var r0 db.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateRoomStateParams) (db.Room, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateRoomStateParams) db.Room); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateRoomStateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorer_UpdateRoomState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoomState'
type MockStorer_UpdateRoomState_Call struct {
	*mock.Call
}

// UpdateRoomState is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateRoomStateParams
func (_e *MockStorer_Expecter) UpdateRoomState(ctx interface{}, arg interface{}) *MockStorer_UpdateRoomState_Call {
	return &MockStorer_UpdateRoomState_Call{Call: _e.mock.On("UpdateRoomState", ctx, arg)}
}

func (_c *MockStorer_UpdateRoomState_Call) Run(run func(ctx context.Context, arg db.UpdateRoomStateParams)) *MockStorer_UpdateRoomState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateRoomStateParams))
	})
	return _c
}

func (_c *MockStorer_UpdateRoomState_Call) Return(_a0 db.Room, _a1 error) *MockStorer_UpdateRoomState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_UpdateRoomState_Call) RunAndReturn(run func(context.Context, db.UpdateRoomStateParams) (db.Room, error)) *MockStorer_UpdateRoomState_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertFibbingItVote provides a mock function with given fields: ctx, arg
func (_m *MockStorer) UpsertFibbingItVote(ctx context.Context, arg db.UpsertFibbingItVoteParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertFibbingItVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpsertFibbingItVoteParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorer_UpsertFibbingItVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertFibbingItVote'
type MockStorer_UpsertFibbingItVote_Call struct {
	*mock.Call
}

// UpsertFibbingItVote is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpsertFibbingItVoteParams
func (_e *MockStorer_Expecter) UpsertFibbingItVote(ctx interface{}, arg interface{}) *MockStorer_UpsertFibbingItVote_Call {
	return &MockStorer_UpsertFibbingItVote_Call{Call: _e.mock.On("UpsertFibbingItVote", ctx, arg)}
}

func (_c *MockStorer_UpsertFibbingItVote_Call) Run(run func(ctx context.Context, arg db.UpsertFibbingItVoteParams)) *MockStorer_UpsertFibbingItVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpsertFibbingItVoteParams))
	})
	return _c
}

func (_c *MockStorer_UpsertFibbingItVote_Call) Return(_a0 error) *MockStorer_UpsertFibbingItVote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorer_UpsertFibbingItVote_Call) RunAndReturn(run func(context.Context, db.UpsertFibbingItVoteParams) error) *MockStorer_UpsertFibbingItVote_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
