// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.937
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

func Toast() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"toast\" x-init=\"globalInit($el)\"><template x-teleport=\"body\"><div class=\"block fixed right-0 bottom-0 mr-4 mb-4 space-y-2.5 z-[999]\" @add-toast.window=\"add\"><template x-for=\"toast in toasts\" :key=\"toast.id\"><div :id=\"toast.id\" x-init=\"toastInit($el)\" x-show=\"toast.show\" x-transition:enter=\"transition ease-out duration-300\" x-transition:enter-start=\"opacity-0 scale-90\" x-transition:enter-end=\"opacity-100 scale-100\" x-transition:leave=\"transition ease-in duration-300\" x-transition:leave-start=\"opacity-100 scale-100\" x-transition:leave-end=\"opacity-0 scale-90\" :class=\"toast.type === 'success' ? 'bg-green': 'bg-red'\" class=\"flex relative gap-2 items-center py-7 px-5 rounded-lg border shadow-sm border-border min-w-[200px] max-w-[384px] sm:min-w-[300px]\"><button @click=\"dismiss(toast.id)\" class=\"absolute top-3 right-3\"><i class=\"hgi hgi-solid hgi-cancel-01\"></i></button><template x-if=\"toast.type === 'success'\"><i class=\"hgi hgi-solid hgi-check-circle\"></i></template><template x-if=\"toast.type === 'info'\"><i class=\"hgi hgi-solid hgi-information-circle\"></i></template><template x-if=\"toast.type === 'warning'\"><i class=\"hgi hgi-solid hgi-alert-triangle\"></i></template><template x-if=\"toast.type === 'failure'\"><i class=\"hgi hgi-solid hgi-cancel-circle\"></i></template><p class=\"text-sm font-medium text-black\" x-text=\"toast.message\"></p></div></template></div></template></div><script type=\"text/javascript\" src=\"/static/js/toast.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
