apiVersion: apps/v1
kind: Deployment
metadata:
  name: banterbus
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.banterbus: "glob:*"
spec:
  selector:
    matchLabels:
      app: banterbus
  template:
    metadata:
      labels:
        app: banterbus
    spec:
      serviceAccountName: banterbus
      nodeSelector:
        node-role: control-plane
      initContainers:
      - name: wait-for-migration
        image: ghcr.io/groundnuty/k8s-wait-for:v2.0
        args:
          - "job"
          - "banterbus-migration"
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      containers:
      - name: banterbus
        image: registry.gitlab.com/hmajid2301/banterbus:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: banterbus-config
        - configMapRef:
            name: banterbus-config-env
        - secretRef:
            name: banterbus-secrets
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets"
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "banterbus-secrets"