apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: banterbus-automation
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@haseebmajid.dev
        name: Flux Image Automation
      messageTemplate: |
        Update banterbus image tags
        
        - Updated {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: main
  update:
    path: "./clusters/apps/banterbus"
    strategy: Setters