apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: banterbus-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: banterbus
      app.kubernetes.io/component: server