apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: banterbus-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: banterbus-rolebinding
subjects:
- kind: ServiceAccount
  name: banterbus
roleRef:
  kind: Role
  name: banterbus-role
  apiGroup: rbac.authorization.k8s.io
