apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: banterbus-secrets
spec:
  provider: vault
  parameters:
    vaultAddress: "https://openbao.homelab.haseebmajid.dev"
    vaultSkipTLSVerify: "true"
    roleName: "k8s-auth-role"
  secretObjects:
  - secretName: banterbus-secrets
    type: Opaque
    data:
    - objectName: db-password
      key: BANTERBUS_DB_PASSWORD