apiVersion: v1
kind: Service
metadata:
  name: banterbus
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: banterbus
    app.kubernetes.io/component: server