// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Player struct {
	ID        string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Avatar    []byte
	Nickname  string
}

type Room struct {
	ID         string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	GameName   string
	HostPlayer string
	RoomState  string
	RoomCode   string
}

type RoomsPlayer struct {
	RoomID    string
	PlayerID  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
