apiVersion: apps/v1
kind: Deployment
metadata:
  name: banterbus
spec:
  replicas: 1
  template:
    spec:
      nodeSelector: null
      containers:
      - name: banterbus
        image: registry.gitlab.com/hmajid2301/banterbus:dev
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
