apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - configmap-patch.yaml
  - deployment-patch.yaml
  - ingress-patch.yaml

images:
  - name: registry.gitlab.com/banterbus/banterbus
    newTag: deploy-latest # {"$imagepolicy": "flux-system:banterbus-dev"}

commonLabels:
  app.kubernetes.io/instance: dev