apiVersion: apps/v1
kind: Deployment
metadata:
  name: banterbus
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: banterbus
        image: registry.gitlab.com/hmajid2301/banterbus:prod
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
