apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.gitlab.com/banterbus/banterbus
    newTag: prod-latest # {"$imagepolicy": "flux-system:banterbus-prod"}

commonLabels:
  app.kubernetes.io/instance: prod