apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: banterbus-secrets
spec:
  parameters:
    objects: |
      - objectName: "db-password"
        secretPath: "kv/data/apps/prod/banterbus"
        secretKey: "db_password"
      - objectName: "db-username"
        secretPath: "kv/data/apps/prod/banterbus"
        secretKey: "db_username"
      - objectName: "oauth2-client-id"
        secretPath: "kv/data/apps/prod/banterbus"
        secretKey: "otel_client_id"
      - objectName: "oauth2-client-secret"
        secretPath: "kv/data/apps/prod/banterbus"
        secretKey: "otel_client_secret"
      - objectName: "oauth2-token-url"
        secretPath: "kv/data/apps/prod/banterbus"
        secretKey: "otel_token_url"
      - objectName: "oauth2-issuer"
        secretPath: "kv/data/apps/prod/banterbus"
        secretKey: "otel_issuer"